### ISSUE TITLE
Wildcard backends or by tag

### ISSUE THREAD

**Issue by cpitt** [joyent/containerpilot#111]
I have a use case with container buddy where I'd like to execute onChange when any service changes or even perhaps when any service with a given tag changes. Based on my reading of the Readme container buddy doesn't currently support this functionality.

**Comment by tgross** [comment]
I like this idea and could certainly see some use cases.

You're correct that wildcards aren't supported. Tags are supported but only for a single backend configuration. Our [`BackendConfig`](https://github.com/joyent/containerbuddy/blob/2f778853fc62f8592da1652f1a2ec4cc8bd49730/containerbuddy/config.go#L78) supports having a tag and we use this tag as a filter when we [check the backend's health](https://github.com/joyent/containerbuddy/blob/2f778853fc62f8592da1652f1a2ec4cc8bd49730/containerbuddy/consul.go#L92). I'll also note that we documented the tags for services but neglected to do so for the backend config so I'll make sure to update the README.

Supporting wildcards is a little tricky from an implementation standpoint. Neither the Etcd and Consul discovery backends don't support wildcards, so for those backends we would need to first get the list of all services, and then make a call for every service individually. (Some future backend might not have this restriction.) For large numbers of services this isn't going to scale very well, and we could easily get into the territory where checking for onChange handlers can overlap with each other. We also don't want to incur the overhead of two requests in the simple case.

Off the top of my head maybe we could split a new `pollingFunc` from the existing [`checkForChanges`](https://github.com/joyent/containerbuddy/blob/2f778853fc62f8592da1652f1a2ec4cc8bd49730/containerbuddy/main.go#L103-L110), and this polling goroutine would only be created in the case where our config has a wildcard. Effectively we'd be saying that the "backends" JSON field is an abstraction around two different implementations.

---

This might take some time to design and implement, so in the meantime I'd like to offer a possible workaround for you.

You can hijack service advertisements to create an artificial group of your applications, and then have your downstream services update based on changes to that service. An `onChange` handler doesn't receive any information from Containerbuddy as to what backend created the change (unless you pass that in the arguments), so we'll take advantage of that here.

Suppose we have 2 similar backend apps like this:

**app1**
```json
{
  "consul": "consul:8500",
  "services": [
    {
      "name": "app1",
      "port": 80,
      "health": "/usr/bin/curl --fail -s http://localhost/health",
      "poll": 5,
      "ttl": 10
    },
    {
      "name": "prod-apps",
      "port": 80,
      "health": "/usr/bin/curl --fail -s http://localhost/health",
      "poll": 5,
      "ttl": 10
    }
  ]
}
```

**app2**
```json
{
  "consul": "consul:8500",
  "services": [
    {
      "name": "app2",
      "port": 80,
      "health": "/usr/bin/curl --fail -s http://localhost/health",
      "poll": 5,
      "ttl": 10
    },
    {
      "name": "prod-apps",
      "port": 80,
      "health": "/usr/bin/curl --fail -s http://localhost/health",
      "poll": 5,
      "ttl": 10
    }
  ]
}
```

Each of the backend apps advertises itself *and* advertises that it belongs to the overall "prod-apps" service. Then your downstream app (let's say it's Nginx), might look like this:

```json
{
  "consul": "consul:8500",
  "services": [
    {
      "name": "nginx",
      "port": 80,
      "health": "/usr/bin/curl --fail -s http://localhost/health",
      "poll": 5,
      "ttl": 10
    },
  "backends": [
    {
      "name": "prod-apps",
      "poll": 3,
      "onChange": [
        "consul-template", "-once", "-consul", "consul:8500", "-template",
        "/etc/containerbuddy/nginx.conf.ctmpl:/etc/nginx/nginx.conf:nginx -s reload"
      ]
    }
  ]
}
```

Your consul-template configuration can load the values of any and all services from Consul, not just the ones that triggered the `onChange` handler. So whenever a "prod-app" changes, Nginx will get the signal and do whatever you configure in your consul-template config. (Or the bash file or confd or whatever you have in the `onChange` handler.)

**Comment by cpitt** [comment]
I think the work around you proposed will work for now, but I do have some reservations about polluting my services with pseudo services. I look forward to seeing what comes from this proposal.

Thanks for the quick response @tgross .

**Comment by misterbisson** [comment]
@cpitt your question and @tgross' suggested workaround reminded me to write up some notes (vague as they may be) on how to register the telemetry interface proposed for Containerbuddy. I did that in https://github.com/joyent/containerbuddy/issues/27#issuecomment-198631596.

I share that here because the approach I described would effectively formalize the workaround, assuming all apps have telemetry activated. And it would be a pseudo-service, it would be a completely valid service.

----

Do you mind, however, sharing more about your use-case? I'd love to better understand it and how you're using (or thinking of using) Containerbuddy.

**Comment by micahlmartin** [comment]
+1 for this functionality. I have an nginx instance that uses consul-template to only render routes for services registered with a tag of `infrastructure`. This is useful for services that have admin interfaces. Currently with containerbuddy I just launch `consul-template` in the background before starting nginx.

**Comment by cpitt** [comment]
I have a similar use case to @micahlmartin. I have two sets of load-balancers internal and external both with n number of services behind them them. I don't want to have to update the containerbuddy configs every time I introduce a new service, but rather have container buddy respond to service tags in consul or service name prefixes. For example anything prefixed with 'int-' or alternatively anything tagged as 'internal' would trigger an on change on my internal load-balancer, while anything prefixed as 'ext-' or alternatively having the tag of 'external' will trigger the on change in the external lb.

I could achieve this like @micahlmartin is currently handling it by launching consul-template as a separate daemon, and using containerbuddy solely for registering the service. However, it seems less than ideal.

**Comment by misterbisson** [comment]
We're leaving this issue open because we can see it's useful, but the complications @tgross pointed out in https://github.com/joyent/containerbuddy/issues/111#issuecomment-198515511 are currently blockers:

> Supporting wildcards is a little tricky from an implementation standpoint. Neither the Etcd and Consul discovery backends support wildcards, so for those backends we would need to first get the list of all services, and then make a call for every service individually. (Some future backend might not have this restriction.) For large numbers of services this isn't going to scale very well, and we could easily get into the territory where checking for onChange handlers can overlap with each other. We also don't want to incur the overhead of two requests in the simple case.
> 
> Off the top of my head maybe we could split a new `pollingFunc` from the existing `checkForChanges`, and this polling goroutine would only be created in the case where our config has a wildcard. Effectively we'd be saying that the "backends" JSON field is an abstraction around two different implementations.

What I'd like to see is support in the back-end service catalogs (Consul and Etcd now, but it's extensible) so we can avoid implementing a very smelly workaround in Containerbuddy.

**Comment by tgross** [comment]
Yeah, that's probably a better approach, @misterbisson

**Comment by tgross** [comment]
We have a workaround proposed for this, and maybe that workaround could be documented somewhere in some detailed use case docs as part of #197 but in the meantime I think it's safe to close this issue in lieu of backend support.
