### ISSUE TITLE
Allow numeric configuration values to be passed as strings

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#122]
Accept a string in place of a number for things like `port` and `ttl` - The change should be backwards compatible - it would accept both numbers and strings which contain a number.

**Use Case**

I have a process that I'm working on that generates a containerbuddy config file. It would be much more useful and maintainable to use the build-in serialization for JSON objects - I can put template definitions into strings, but it's impossible to do the same for numbers. A work around would be to concatenate strings together to form a JSON document instead of using a serializer - which is not ideal.

**Comment by tgross** [comment]
Sounds good to me.

**Comment by tgross** [comment]
> I have a process that I'm working on that generates a containerbuddy config file. It would be much more useful and maintainable to use the build-in serialization for JSON objects

Just out of curiosity, what language/library is this? JSON serialization without support numeric types is surprising (most of the stdlibs I've worked with have it).

**Comment by justenwalker** [comment]
I'm using go.  It has support for numbers - the problem is this is not valid JSON so I can't deserialize it using the normal method:

```json
{
  "key": {{ .ENV_PORT }}
}
```

**Comment by misterbisson** [comment]
@justenwalker I see your use case, and now I'm curious about what's behind it ;-)

As @tgross said, this sounds good.

**Comment by tgross** [comment]
Was covered in https://github.com/joyent/containerpilot/issues/138

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.1.1
