### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#124]
In https://github.com/joyent/containerbuddy/pull/119 @justenwalker wrote:
> But to the README point - it seems like that is getting quite big and will continue to grow. Is there call for generating some kind of webpage and splitting out the concepts into a more organized format? 

I had a discussion with @misterbisson about this a week or so ago and we both definitely think we should re-org the documentation. We unfortunately failed to open a GitHub issue about it to discuss it in the open. So let's correct that now!

I think whatever documentation we have needs to serve a bunch of different purposes:
- "what the heck is this?" (top-level)
- "why use this?"
- "how do you configure this?"
- "why does this work the way it does?" (theory of operation)
- "how does this fit in the context of my architecture?" (big-picture)
- "can you show me examples?"

@justenwalker wrote:
> Would be good to include such a 'website' in the same repo and generate the page somehow. (isn't that what github.io does? I haven't tried it)

That's GitHub pages, and it's a good option for web presence (I use it for https://github.com/tgross/tgross.github.io too). We currently have containerbuddy.io but that's a manual scrape of the README that then gets dumped into [Kirby](https://getkirby.com/). I'd be open to the idea of using GitHub pages here because it's such a project-specific page but I think there might be some "we should be dogfooding" questions at Joyent to answer about that first. Let me check in internally about that and circle back on this later.

I think that whatever we do we'll probably want to make available as README / markdown in the repo so that it's obvious where people can contribute edits. The small trouble with `gh-pages` is the workflow when combined with documentation updates for a feature (i.e. do you make 2 PRs -- one for code and one for docs?). A better approach to that workflow might be to have the markdown live in READMEs in master but then have a `make` target that publishes updates to the `gh-pages` branch.

**Comment by justenwalker** [comment]
> I think that whatever we do we'll probably want to make available as README / markdown in the repo so that it's obvious where people can contribute edits. The small trouble with gh-pages is the workflow when combined with documentation updates for a feature (i.e. do you make 2 PRs -- one for code and one for docs?). A better approach to that workflow might be to have the markdown live in READMEs in master but then have a make target that publishes updates to the gh-pages branch.

If i'm not mistaken, [readthedocs](https://readthedocs.org/) might do something like this. Although I'm not sure how much control you have over branding / designing the page.

**Comment by tgross** [comment]
> We currently have containerbuddy.io but that's a manual scrape of the README that then gets dumped into Kirby.

That domain is now a redirect to http://joyent.com/containerpilot, which probably makes the Kirby question moot. The *Read the Docs* equivalent for golang is usually [godoc](https://godoc.org/) but that's more geared towards API documentation and not the bigger picture stuff that we want to cover here. But for now I think I'd rather worry more about the content of the docs than how we serve them up -- it's easy to change that later.

**Comment by tgross** [comment]
An item missing from the big list of topics above: "how do I usefully contribute to the project?" Give people some guidelines around contributing code and writing tests, and a quick guide to the GitHub labels we're using (I'm thinking of changing "help wanted" to "easy", to mean "hey this would be a good issue to tackle if you're just getting started with contributing").

**Comment by justenwalker** [comment]
> But for now I think I'd rather worry more about the content of the docs than how we serve them up

They might go hand-in-hand though - depending on the technology used for hosting them.

> I'm thinking of changing "help wanted" to "easy"

"easy" might not convey the right meaning.  Perhaps something like `contributions-welcome` says it more directly for the people who don't immediately gravitate towards the CONTRIBUTING.md file

On that note though, would it make sense to move the thanks section to `AUTHORS`? It is customary for a lot of open source projects (see [golang](https://golang.org/AUTHORS)). That way, we focus CONTRIBUTING.md as a guide for new contributors, since it shows up as suggested reading when making a PR or an issue.

**Comment by tgross** [comment]
Covered by https://github.com/joyent/containerpilot/pull/167
