### ISSUE TITLE
Container config from consul?

### ISSUE THREAD

**Issue by magnayn** [joyent/containerpilot#131]
This isn't really an issue rather a question (and I couldn't tell from the blog post if there is anywhere else to discuss).

I was intrigued by the autopilot pattern, and I have been looking at the autopilot jenkins example.

The mechanism of burning certain configuration parameters into the image (the _env file) feels unfortunate, as it means (if I follow the pattern for our services) I'd need to create a fresh image for every individual instance I run (and every time a configuration item changed). This is contrary to what our CI process would like - broadly - 'the same image for every install'.

This is often achieved by a 'configuration' container (e.g: for Jenkins this would either map jenkins_home to a separate container, or parent filesystem path) - thus upgrades are rather simple (pull the latest image version, restart).

Another route that I assumed the autopilot/jenkins would do would be to pull those values from the consul key/value store (under jenkins+hostname+config as a key, perhaps).

To do that presumably I might want to be informed if the config changes (to perhaps restart), or it might cause me to want to register for notifications to further key changes. I also don't know what that means for security (if the admin password is in consul, is there a shared secret to decrypt passed at startup time to the container, etc., etc).

So, err - just mumbling out loud.. is any of that reasonable, or is that not something you feel is the right way to go?

**Comment by tgross** [comment]
@magnayn I think you're on fundamentally asking if it is feasible for ContainerPilot configurations to be configured at runtime?

Yes! You've got a couple options here. The first is to inject the ContainerPilot configuration via whatever you're using to launch containers (ex. a scheduler) via the `CONTAINERPILOT` environment variable. The second, and maybe more along the lines of what you might be thinking, is to have ContainerPilot's `preStart` mechanism fetch a configuration file from Consul and then fire a SIGHUP to reload itself. You could then ship a ContainerPilot config in your Docker image that looks like:

```json
{
  "consul": "{{ .CONSUL }}:8500",
  "preStart": "/get-containerpilot-config.sh"
}
```

And then include a `get-containerpilot-config.sh` script that does something like this:

```bash
#!/bin/bash

curl -s --fail ${CONSUL}:8500/v1/kv/containerpilot/template?raw > /tmp/containerpilot.json.ctmpl
consul-template \
    -once \
    -consul ${CONSUL}:8500 \
    -template "/tmp/containerpilot.json.ctmpl:/etc/containerpilot.json:kill -HUP 1"
```

We do something similar to this in https://github.com/autopilotpattern/nginx where the virtualhost config is fetched from Consul.

> I also don't know what that means for security (if the admin password is in consul, is there a shared secret to decrypt passed at startup time to the container, etc., etc).

We've been agnostic about how to inject secrets, partially because the solutions out there all depend a lot on how you're issuing secrets overall. One thing we've been wanting to try out is using [Hashicorp's Vault](https://www.vaultproject.io/) alongside or within our Consul containers; I'd love to see what you come up with if you give that a try.

**Comment by adamlc** [comment]
Thanks for the description @tgross. We're actually in a similar position. We currently use Vault in production along with consul-template and have been working out the best way of getting all this to work properly.

We're actually trying to get over a couple of things relating to vault and containerpilot. The first issue is getting the authentication token from vault into the container (although this is actually outside the scope of CP anyway). Hashicorp have some interesting theories on the best way to do this, have a read of this article (https://www.hashicorp.com/blog/vault-cubbyhole-principles.html). The tldr version is to inject the auth token into the container using a well known method, such as a single HTTP post. It would be great if we could somehow do this within CP.

I'm not sure if there is a script timeout on the preStart but I basically wanted to try what I've mentioned above by running a HTTP server and waiting for the token and once that is complete actually get container buddy to start, or something along those lines. I'm still experimenting at the moment but its great to hear other people are having similar issues and are thinking about a solution :)

**Comment by tgross** [comment]
@adamlc thanks for that link... I'm out at a conference today but I'll dig into this over the weekend and have some more cogent thoughts on it next week.

**Comment by magnayn** [comment]
Is there a ML for these kinds of things? It feels like there's lots of good stuff going on and people solving similar problems. It feels very much like this is the "Inversion of Control" pattern, but for infrastructure.

I was very influenced by the "cattle, not pets" view for how container infrastructures should run. Today, our software (when dockerised) operates fairly similarly to jenkins (dockerised) - there's one immutable 'product' container that links to a 'configuration' container, which is built containing all the particulars of that deployment.

One grey area seems to be "plugins". Similar to jenkins, we do a 'drop jar file in directory, system auto-expands and installs without a restart required.

If I allow this in the 'config' container, I'm making runtime config changes, it's no longer immutable. If I don't (and force the config to be built from a Dockerfile, pulling in plugins into that config container) I have to restart the system to apply what used to be a 'drop file in directory' operation. It feels maybe plugins need to be procured from an external registry, and the config just maintains a list of what versions it's using.

**Comment by tgross** [comment]
> Is there a ML for these kinds of things?

There isn't but we have a new Gitter chat at https://gitter.im/autopilotpattern/general.

> One grey area seems to be "plugins". Similar to jenkins, we do a 'drop jar file in directory, system auto-expands and installs without a restart required.
> If I allow this in the 'config' container, I'm making runtime config changes, it's no longer immutable.

I've done a not-widely-published-and-not-super-polished [Jenkins](https://github.com/autopilotpattern/jenkins) setup for the autopilot pattern and we've been [working](https://github.com/autopilotpattern/wordpress/pull/1) with some folks on a Wordpress demonstration and ran into this question. In both cases I'm of the opinion that if you're not packaging these plugins in with the container image then you're risking a serious case of "works on my machine." The only thing that should vary are the environment-specific configuration.

**Comment by tgross** [comment]
Going to tag this as `docs` just so that it's been officially triaged and maybe so that we can bring some of these ideas into the documentation / FAQ rework in https://github.com/joyent/containerpilot/issues/124

**Comment by justenwalker** [comment]
@adamlc, Since we've added periodic tasks to [2.1.0](https://github.com/joyent/containerpilot/releases/tag/2.1.0), could you run consul-template that way instead?

**Comment by adamlc** [comment]
@justenwalker it certainly sounds like that might work! My application requires the settings that consul template generates to startup. At the moment I already have a preStart script, so I'll have to adapt that to also run consul-template before the application starts up!

**Comment by wleese** [comment]
Ran into this: https://github.com/joyent/containerpilot/pull/140
Maybe I'm doing something wrong, but a sighup from prestart scripts simply kills containerpilot-2.1.0 at the moment

**Comment by tgross** [comment]
Good call on that @wleese. Added a comment in the PR.

**Comment by tgross** [comment]
https://github.com/joyent/containerpilot/pull/167
