### ISSUE TITLE
Docs: Add note about process logs

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#137]
Since #134 has been merged, output of the ContainerPilot processes are piped directly into the logging framework.  From the README:

> ContainerPilot also attaches stdout/stderr from your application to stdout/stderr of the container, so that docker logs works as expected.

Although this is true, we may want to mention that service health checks, lifecycle hooks (preStart, preStop, postStop) and tasks will have their output piped to the ContainerPilot logging framework and are configurable with the `logging` section.

From the discussion:

> But for a process we take a different approach and instead:
> ```go
stdout := utils.NewLogWriter(fields, log.InfoLevel)
stderr := utils.NewLogWriter(fields, log.DebugLevel)
cmd.Stdout = stdout
cmd.Stderr = stderr
```
> This means that all process output is shipped to the log which can be adjusted with the log config.

**Comment by tgross** [comment]
Good call. Want to add that to https://github.com/joyent/containerpilot/pull/136 ?

**Comment by justenwalker** [comment]
@tgross Yeah I will. Also discovered some more fixes to the docs I'll apply along with that.

**Comment by tgross** [comment]
Merged!
