### ISSUE TITLE
Have health checks timeout

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#139]
I've run into an issue where a health check hangs because of something unrelated to ContainerPilot. The underlying problem seems to right itself, but because the health check hangs the container never becomes healthy.

If we port the [timeout functionality from the new tasks feature](https://github.com/joyent/containerpilot/blob/cea9070df36d4bd5795142af2d2dbcb4d17e4035/tasks/tasks.go#L128-L141) to health checks and other user-defined behaviors we could avoid situations where a machine that can become healthy if the health check is given a chance to re-run doesn't do so.

**Comment by justenwalker** [comment]
@tgross Should that be a feature of all `Pollables` ?

**Comment by tgross** [comment]
Yeah, I think that makes sense.

**Comment by tgross** [comment]
Would be worth looking at https://github.com/docker/docker/pull/23218/files#diff-e9ee36fa14ba54512c7e7b0918c7b1d0R147 for what looks to be a pretty robust timeout on child processes done by the Docker team.

**Comment by tgross** [comment]
I'm going to take this on and move some of the exec/wait stuff current in utils into a `commands` package that wraps the `exec.Cmd` interface with the timeout behaviors we want here.

**Comment by javabean** [comment]
In the mean time, you can use the [timeout](http://linux.die.net/man/1/timeout) unix utility in your health check command.

**Comment by tgross** [comment]
I've laid the groundwork for this in #184 so now I just need to add the configuration options for it.

**Comment by tgross** [comment]
TravisCI is showing a failing integration test that works locally and worked in the PR but not the most recent master build: https://travis-ci.org/joyent/containerpilot/builds/149271893

```
2016/08/02 18:50:46 TEST: test_tasks
Creating testtasks_consul_1
testtasks_consul_1 is up-to-date
Creating testtasks_app_1
Expected task1 to never time out: got 1
No stopped containers
2016/08/02 18:50:54 FAIL: test_tasks
```

I kicked off the build again because I think the failure is transient but that's no good so I need to figure out what I broke.

**Comment by tgross** [comment]
Ok I've dug into that previously-failed build https://travis-ci.org/joyent/containerpilot/builds/144807746. That build is on commit https://github.com/joyent/containerpilot/commit/cbd5181292c9a0313d29958b2c9e0380490a1a8a which was rebased-away (curse you past me for wanting clean commit history!) to become https://github.com/joyent/containerpilot/pull/184/commits/aa3d659cbe6c002b5e345d2bb2463d2ac61f2f30.

The original commit did not include the fixes to task log parsing in https://github.com/tgross/containerpilot/commit/f8de2c76d4cc0cb38593ffc35aed40989f56b85f and that's the source of the failed build.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.4.0
