### ISSUE TITLE
Refactor Discovery Backend Registration

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#143]
As we are going to support multiple backends, it would be good if we didn't have to alter global config parser so much.

I propose that we make the config more free-form (`map[string]interface{}`) and support hooking into keys using a Registration function. Discovery backends could call this registration in their `func init() { ... }` to register a handler for their key ("consul", "etcd", "zookeeper", ...)

I'll try an initial PR to get the idea out in a more concrete form. I think this will significantly improve how we parse the configuration file. 

As a part of this enhancement, it would be good to push the discovery backends into their own package.

**Comment by tgross** [comment]
Merged in https://github.com/joyent/containerpilot/issues/144. I'm building a release for this now.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.1.1
