### ISSUE TITLE
Investigate timing issue in tasks test

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#146]
@justenwalker wrote in https://github.com/joyent/containerpilot/pull/144#issuecomment-217302376:

> Seems like there is some timing bug in the tasks test.

The build in question is https://travis-ci.org/joyent/containerpilot/builds/128126162 which passed when we re-pushed it. Here's the failing test:

> 2016/05/05 19:28:30 TEST: test_tasks
Creating testtasks_consul_1
testtasks_consul_1 is up-to-date
Creating testtasks_app_1
Expected task1 to have 7 executions: got 8
Expected task3 to have 2 executions: got 3
No stopped containers
2016/05/05 19:28:39 FAIL: test_tasks

**Comment by justenwalker** [comment]
I have a feeling it is something to do with the timing of the measurement, somehow it got delayed and these tasks were allowed an extra execution.

I think we have to 
- loosen the timings a bit more to account for variance
- make the expected result depend on the time measured
- find another way to test this which doesn't have this variance

**Comment by tgross** [comment]
Closed in https://github.com/joyent/containerpilot/pull/152
