### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#148]
Currently our builds are creating lint errors. In order to keep code quality high, we should consider fixing them.

- Fix all lint errors output by `golint`
- Cause lint errors to fail the build - thereby encouraging higher quality commits and more immediate feedback.

**Comment by tgross** [comment]
As much as I think golang is overly opinionated about this stuff, I agree that it's a good idea to give linting feedback in PRs.

Below I'm adding some pointers for anyone who wants to pick this up; the latest build can always be found at https://travis-ci.org/joyent/containerpilot. Here's the latest lint run, with the problems broken out by package:

`backends`
> /cp/src/github.com/joyent/containerpilot/backends/backends.go:24:1: exported function NewBackends should have comment or be unexported
/cp/src/github.com/joyent/containerpilot/backends/backends.go:28:2: can probably use "var backends []*Backend" instead

`config`

> /cp/src/github.com/joyent/containerpilot/config/template.go:28:6: type name will be used as config.ConfigTemplate by other packages, and that stutters; consider calling this Template
/cp/src/github.com/joyent/containerpilot/discovery/discovery.go:7:6: type name will be used as discovery.DiscoveryService by other packages, and that stutters; consider calling this Service
/cp/src/github.com/joyent/containerpilot/discovery/discovery.go:22:2: struct field IpAddress should be IPAddress

`discovery/etcd`
> /cp/src/github.com/joyent/containerpilot/discovery/etcd/etcd.go:29:6: type name will be used as etcd.EtcdServiceNode by other packages, and that stutters; consider calling this ServiceNode

`services`
> /cp/src/github.com/joyent/containerpilot/services/services.go:30:1: exported function NewServices should have comment or be unexported
/cp/src/github.com/joyent/containerpilot/services/services.go:46:1: exported function NewService should have comment or be unexported
/cp/src/github.com/joyent/containerpilot/services/services.go:83:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
/cp/src/github.com/joyent/containerpilot/services/services.go:94:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
Found 4 lint suggestions; failing.

`telemetry`
> /cp/src/github.com/joyent/containerpilot/telemetry/sensors.go:61:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
/cp/src/github.com/joyent/containerpilot/telemetry/sensors.go:90:1: exported function NewSensors should have comment or be unexported
/cp/src/github.com/joyent/containerpilot/telemetry/sensors.go:91:2: can probably use "var sensors []*Sensor" instead
/cp/src/github.com/joyent/containerpilot/telemetry/sensors.go:98:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)

**Comment by tgross** [comment]
Closed in https://github.com/joyent/containerpilot/pull/151
