### ISSUE TITLE
using consul ACL with containerpilot

### ISSUE THREAD

**Issue by ric03uec** [joyent/containerpilot#153]
We (at shippable) are experimenting with `containerpilot` as an implementation for `autopilot` pattern. The problem we're running into is when using `consul` ACL with `containerpilot`. The ACL works well with `consul-template` that supports it out of box so all our use cases are supported by default.
- Does `containerpilot` have support for `consul` ACL? I went through the docs but could'nt find any way to do this. 
- Is there any way to make authorization work with `containerpilot`.
We cannot give client `containerpilot` instances the ability to access all of consul data and would ideally want to restrict one instance to a predefined namespace  
Thanks

**Comment by misterbisson** [comment]
@ric03uec ContainerPilot doesn't support [Consul ACLs](https://www.consul.io/docs/internals/acl.html) _today_, but it's a feature I'd love to support. 

Can you start us off by sharing some use-cases and how users might configure them on the ContainerPilot side?

**Comment by ric03uec** [comment]
@misterbisson thanks for the quick response.

We're trying to support the following use-case'

1. Set the `acl_default_policy` of the consul cluster to `deny`
2. Admin navigates to `consul`, ACL page and creates a new ACL(say `serviceACL) with following policy
```
service "foo-" {
  policy: "write"
}
```
This generates a token, say `serviceFooPolicyToken` that can now manipulate any services starting with `foo-` 
3. boot a service `foo-api` using `containerpilot` that uses the token ` serviceFooPolicyToken`. This service should now be registered into `consul` cluster
4. boot a service `foo-ui` using `containerpilot` that uses the token `serviceFooPolicyToken`. This should have `foo-api` as its dependency. `containerpilot` should be able to register this service and get the status of `foo-api` service also because of the correct token
5. boot a service `bar-ui` using `containerpilot` that uses the token `someRandomToken`. `bar-ui` should **not** be able to get the status or even list `foo-api` and `foo-ui`. registration of `bar-ui` should also fail if `someRandomToken` is not a valid token for any ACL

The basic idea to enable namespace based boundaries for resources. enabling ACL will help us get that working. **THE** best solution would be to have ACL and an explicit field called `namespace` in the config file, something like
```
{
  "consul" : "localhost:8500",
  "token" : "sometoken",
  "namespace": "foo",
  ... other configs
}
```
But i think this will require changes in `consul` itself.

**Comment by tgross** [comment]
@ric03uec I haven't done an implementation of this myself but our Consul backend supports using the `CONSUL_HTTP_TOKEN` environment variable (ref https://github.com/joyent/containerpilot/issues/78 and https://github.com/joyent/containerpilot/pull/79) which should be setting the ACL for the client on per-request basis via the `X-Consul-Token` header as described in the HTTP client docs (https://www.consul.io/docs/agent/http.html).

I'm going to test this end-to-end this morning though to make sure that we've implemented the right thing for your scenario.

**Comment by tgross** [comment]
Ok, so I tested this out and I think it works as expected @ric03uec.

I took the stack at https://github.com/autopilotpattern/workshop and gave Consul the following configuration file:

```
{
  "acl_datacenter": "dc1",
  "acl_default_policy": "deny",
  "acl_master_token": "abcdef",
  "data_dir": "/data",
  "ui_dir": "/ui",
  "client_addr": "0.0.0.0",
  "ports": {
    "dns": 53
  },
  "recursor": "8.8.8.8",
  "disable_update_check": true
}
```

I then used the Consul console to give myself the master token at http://localhost:8500/ui/?token=abcdef#/dc1/settings and used that to set up the ACLs at http://localhost:8500/ui/?token=abcdef#/dc1/acls. I used this rule:

```
service "nginx-" {
    policy = "write"
}

service "customers-" {
    policy = "write"
}
```

And then I added that ACL token to the Nginx and Customers applications only:
```
environment:
    - CONSUL_HTTP_TOKEN=d9e15f13-ea39-6184-049b-ab6c69d68570
```

When I did this, the Nginx and Customers applications were able to register with Consul and Nginx was able to get the Customers application IPs. But the Sales application was unable to register (as expected) and we get the following warning in the Consul logs:

> 2016/05/12 14:27:25 [WARN] consul.catalog: Register of service 'sales' on '3b21630c5ce0' denied due to ACLs

With this, I believe we've verified that we have the correct behavior for the Consul ACLs. I'll open a PR making it clear in the documentation around Consul configuration that we accept the environment variable.

**Comment by tgross** [comment]
https://github.com/joyent/containerpilot/issues/156 has been merged. @ric03uec I'm going to close this issue for now because I think it was just the documentation problem. If you're seeing problems when you tackle it please feel free to re-open this issue and we'll get down to it.

**Comment by ric03uec** [comment]
@tgross @misterbisson thanks for the update. will try this out and re-open if i face any issues
