### ISSUE TITLE
Expose ContainerPilot state and configuration through telemetry interface

### ISSUE THREAD

**Issue by misterbisson** [joyent/containerpilot#154]
We introduced [application telemetry in ContainerPilot 2.0](https://www.joyent.com/blog/containerpilot-telemetry) as discussed in https://github.com/joyent/containerpilot/issues/27, but some of the features there remain. Specifically, those described in https://github.com/joyent/containerpilot/issues/27#issuecomment-207462572:

> In addition to the application performance metrics that can be used to support scaling decisions, this interface can provide a number of details that are known to Containerbuddy:
> - The service(s) provided by the container, what ports they're on
> - Their current health
> - The names of upstream services the container depends on
> 
> Using that information, a consumer application can traverse the all the containers in an application, graph their relationship, and display a visual representation of the entire application, its health, and performance.

...and from https://github.com/joyent/containerpilot/issues/135#issuecomment-211513745:

> The telemetry service [...] represents ContainerPilot itself. The roadmap for the telemetry service includes presenting additional metadata about the container. Predictability in the service name is intended as a way to simplify the development of consumers and new thinking about how this data can be used.

**Comment by justenwalker** [comment]
Would this be another HTTP endpoint (eg: `/status` ) responding with this data as a JSON object?
To what schema would that JSON object conform? I don't really know of an existing schema, so we'd possibly be inventing one here.

Unfortunately, these characteristics do not fit to any metric type. Perhaps we could abuse gauge by alternating between 1 and 0 for each service name to indicate health - but it would be icky.

For reference, [Metric Types](https://prometheus.io/docs/concepts/metric_types/) are:

- **counter** - A counter is a cumulative metric that represents a single numerical value that only ever goes up.
- **guage** - A gauge is a metric that represents a single numerical value that can arbitrarily go up and down.
- **histogram** - A histogram samples observations and counts them in configurable buckets. It also provides a sum of all observed values.
- **summary** - A summary samples observations. While it also provides a total count of observations and a sum of all observed values, it calculates configurable quantiles over a sliding time window.

**Comment by misterbisson** [comment]
> Unfortunately, these characteristics do not fit to any metric type

Agreed, this should not be wedged into the metrics data, and Prometheus (as it exists today) is not a likely consumer.

> I don't really know of an existing schema, so we'd possibly be inventing one here

Right. Action here is awaiting some use-cases to help define what needs to be in there, which might help identify useable prior art.

**Comment by tgross** [comment]
A starting point for discussion might be exposing the ContainerPilot configuration file JSON? This way an outside service could hit that endpoint and find out almost everything listed in @misterbisson's top-level comment here. Well except for health of a service -- ContainerPilot doesn't know the state of health currently, only the instantaneous health. And it never knows the health of upstreams; it only has a list of healthy upstreams (and never hears about unhealthy ones). I guess we could store the exit code of pollables and serve that up in the JSON body though.

**Comment by justenwalker** [comment]
@tgross If we're going to expose the entire config, It should probably be undecorated. We load it, render it using the template engine, then store the rendered results in memory - and just serve up that raw content via a `/config` endpoint.

Then later we have a `/status` endpoint for getting the current internal state.

**Comment by justenwalker** [comment]
A cause for concern with having the `/config` endpoint is that it may expose secrets. If we were to support that, we'd have to make it very clear that you shouldn't refrence secrets in environment variables that you interpolate in consul template config.

**Comment by tgross** [comment]
Ugh, yeah. That's a very good point.

**Comment by tgross** [comment]
https://github.com/joyent/containerpilot/issues/244 has been opened as a proposal to cover this issue as a 2.x-compatible enhancement.

**Comment by tgross** [comment]
Although a lot of the work to make this work will be done as part of 3.0.0, we don't have the planned consumer for the status endpoint yet and won't have a solid draft of this for some time. Fortunately this endpoint can be added in a backwards-compatible way, so I'm going to mark this issue as 3.x rather than a blocker for 3.0.0

**Comment by tgross** [comment]
The `depends_on` fields [in the RFD](https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md#getstatus-get-status) aren't really going to work as we thought. The concept of a service "depending upon" some external service would be misleading to tell the user.

So instead after some discussion with @geek we're going to separate out the `services` (advertised jobs) from the `watches`. The `/status` endpoint will return the following:

```json
{
  "services": [
    {
      "name": "nginx",
      "address": "192.168.1.100",
      "port": 80,
      "status": "healthy"
    }
  ],
  "watches": [
    "myBackend",
    "myOtherBackend"
  ]
}
```

**Comment by tgross** [comment]
Implementation notes for myself for later:

The last good place to initialize the telemetry server is [here](https://github.com/joyent/containerpilot/blob/d0d24cb6ed738ee830add88433ab62b4381e85d5/core/app.go#L199) in `core/NewApp` because after that we just hit `Run`. We'll want to add a pointer to the jobs struct to the `Telemetry` struct because we don't just need to report the static information but we also need to be able to call [`Job.GetStatus`](https://github.com/joyent/containerpilot/blob/d0d24cb6ed738ee830add88433ab62b4381e85d5/jobs/jobs.go#L110-L116)

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.1.0
