### ISSUE TITLE
Should we continue to trap SIGUSR1?

### ISSUE THREAD

**Issue by misterbisson** [joyent/containerpilot#161]
From the readme:

> `SIGUSR1` will cause ContainerPilot to mark its advertised service for maintenance. ContainerPilot will stop sending heartbeat messages to the discovery service. The discovery service backend's `MarkForMaintenance` method will also be called (in the default Consul implementation, this deregisters the node from Consul).

This was intended to support graceful shutdowns of applications prior to updates, but the functionality was incorporated into the normal shutdown behavior via `SIGTERM` with a configurable `stopTimeout` value.

We might consider deprecating this feature now so that we don't risk conflicting with a user's apps and needs for limited signal space in the future for a feature that hasn't been used in production (to my knowledge) and has what appears to be a cleaner solution elsewhere (the `SIGTERM` behavior).

**Comment by tgross** [comment]
> This was intended to support graceful shutdowns of applications prior to updates

It also allows you to remove an instance from production usage but keep it running, which is highly useful for debugging against live systems. If you `SIGTERM` the instance you can't core dump it, put `mdb`/`gdb` on it, etc. Although we at Joyent like our DTrace and can safely debug systems that are in the middle of handling live production traffic, environments without DTrace will tend to want to yank an instance that's in an ["implicit non-fatal failure"](https://youtu.be/sYQ8j02wbCY?t=1348) condition so they can be checked out but not shut down the process.

**Comment by misterbisson** [comment]
That's clear. Thanks.
