### ISSUE TITLE
Container pilot reload bug

### ISSUE THREAD

**Issue by mterron** [joyent/containerpilot#163]
When issuing a SIGHUP to the containerpilot process to reload it's config, I see his:
[TIMESTAMP] Reloading configuration.
[TIMESTAMP] Error initializing config: -config flag is required

The environment variable pointing to the containerpilot configuration file exists and that's the way the container started up with no problem.

How to reproduce: 

1. Edit CP configuration file
2. pkill -SIGHUP containerpilot

**Comment by tgross** [comment]
@mterron there's a PR open for this here: https://github.com/joyent/containerpilot/pull/159 but it's run into a test breakage. Will be looking into this later today as well.

**Comment by tgross** [comment]
Fix released in https://github.com/joyent/containerpilot/releases/tag/2.1.3
