### ISSUE TITLE
Consul availability timeout

### ISSUE THREAD

**Issue by mterron** [joyent/containerpilot#164]
I'd like to be able to configure a period of time to wait for Consul to be available before killing the container on startup (configurable).
At the moment I'm running this script as CMD in all my CP containers: [https://github.com/mterron/logstash-autopilot/blob/master/bin/prestart.sh](https://github.com/mterron/logstash-autopilot/blob/18a55c1a7405efb89248bbfa26e913d54367cb98/bin/prestart.sh)

This is useful when Consul is part of the composition you will run.

**Comment by tgross** [comment]
That could go in a `preStart` script in most circumstances, but I agree that having some way to wait for the discovery service to be available before starting up would be a good idea.

**Comment by tgross** [comment]
@mterron I've updated your link to a specific commit so that it doesn't 404 on us in the future.

**Comment by tgross** [comment]
Marking this as a 2.x-compatible enhancement.

**Comment by tgross** [comment]
This will be available in v3 as part of the new configuration model. Each service (which now includes what in v2 was preStart, preStop, postStop, coprocess, and task) will be able to set a start timeout. 

Ground work for this has been released in #290 and I'll add the config hooks for it during the v3 config update. Refer to [RFD86](https://github.com/joyent/rfd/blob/master/rfd/0086/README.md) and the v3 roadmap in #283 for details.

**Comment by tgross** [comment]
Implemented in https://github.com/joyent/containerpilot/pull/312

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.2
