### ISSUE TITLE
Allow telemetry server port to change on reload

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#166]
As per https://github.com/joyent/containerpilot/pull/165 and https://github.com/joyent/containerpilot/pull/123#issuecomment-208455770, the native golang HTTP server cannot be reloaded gracefully if we're on the same port. We backed out the change to try this in order to fix the bug, but this is something we definitely should support. There are a couple options here as I see it:
- Only attempt to reload the server if the port changes, and then just kill the old server. This would require some changes to what we pass into NewTelemetry because right now we don't consider the old Telemetry struct at all.
- Find a working library for graceful server reload that handles the socket correctly and replace the native server with that.

cc @misterbisson and @justenwalker for discussion

**Comment by tgross** [comment]
@justenwalker wrote:
> There are wrappers around the http package that support reload though we might consider using: (See [graceful.go](https://github.com/tylerb/graceful/blob/master/graceful.go))

This seems to be the sort of thing we want but the developer is using gopkg.in so we'll need to fork them if we wanted to use it.

**Comment by justenwalker** [comment]
If it's only a single go file under MIT license, we could possibly just copy the source we need provided we meet the MIT license requirements (which are [minimal](http://choosealicense.com/licenses/mit/))

**Comment by tgross** [comment]
Oh, it looks like the author hasn't done something that another widely used library that shall remain nameless [\**cough*\*](https://github.com/go-yaml/yaml/tree/master) did, which is break `master` so that *only* gopkg.in works. We should be able use graceful using Godeps normally. Assuming it does  the job for us, of course.

**Comment by tgross** [comment]
Marking this as a 2.x-compatible enhancement.

**Comment by tgross** [comment]
This was added as a feature in golang1.8, which we'll support in v3

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3
