### ISSUE TITLE
Add consul token

### ISSUE THREAD

**Issue by mterron** [joyent/containerpilot#168]
When using ACL you have to present a token to Consul. Add the option to define the token in the configuration file.

**Comment by tgross** [comment]
We currently support using the `CONSUL_HTTP_TOKEN` environment variable for ACL (ref https://github.com/joyent/containerpilot/issues/153). Adding it to the configuration file will typically mean baking credentials into the image. Is that really a model we want to support?

**Comment by mterron** [comment]
I couldn't find a reference to that Tim, sorry. You can close this one.
Thanks

**Comment by tgross** [comment]
Sounds good!
