### ISSUE TITLE
Consul client certificate

### ISSUE THREAD

**Issue by mterron** [joyent/containerpilot#169]
When using a secured Consul, you need to present a client certificate to the http api. Please add the option to define the client certificate in the ContainerPilot config file.

Currently you get this error when CP tries to register a service:
`2016/06/01 15:09:18 Service registration failed: Put https://consul.service.consul:8501/v1/agent/service/register: remote error: bad certificate`

And this when it tries to query for one:
`2016/06/01 15:09:08 Failed to query elasticsearch-master: Get https://consul.service.consul:8501/v1/health/service/elasticsearch-master?passing=1: remote error: bad certificate [<nil>]`

**Comment by tgross** [comment]
:+1: on this as a proposal. It looks like we need to create a [TLSConfig](https://godoc.org/github.com/hashicorp/consul/api#TLSConfig), but it's not clear to me from a cursory look at the Consul API docs how to actually use it. I'd expect something like a `Config` interface being passed into the `NewClient` but `Config` is a struct type not an interface. Will need to dig into it some more but this would be a great spot for a community contrib as well.

**Comment by mterron** [comment]
### Caveat Emptor, I don't **_know_** Golang, so this is just an educated guess 
@tgross Config is a struct and TLSConfig is also a struct, see: https://github.com/hashicorp/consul/blob/a440433ac832516bb026872f698669122a4789b6/api/api.go so from that point of view both work the same way. At https://github.com/joyent/containerpilot/blob/2bdab142a7ba14a050c7e7913088dc94de0001ec/discovery/consul/consul.go configFromMap config is a struct
```go
func configFromMap(raw map[string]interface{}) (*consul.Config, error) {
	config := &struct {
		Address string `mapstructure:"address"`
		Scheme  string `mapstructure:"scheme"`
		Token   string `mapstructure:"token"`
	}{}
	if err := utils.DecodeRaw(raw, config); err != nil {
		return nil, err
	}
	return &consul.Config{
		Address: config.Address,
		Scheme:  config.Scheme,
		Token:   config.Token,
	}, nil
}
```
that is missing some bits for TLS (CAFile, CertFile,KeyFile).

The function defaultConfig https://github.com/hashicorp/consul/blob/a440433ac832516bb026872f698669122a4789b6/api/api.go @ line 216 actually check if https is the scheme and verify is required and set up a TLSConfig.

**Comment by tgross** [comment]
> Config is a struct and TLSConfig is also a struct

In golang what you're looking for there is that they both implement an `interface` by implementing that `interface`'s methods. But in this case...

> The function defaultConfig ...@ line 216 actually check if https is the scheme and verify is required and set up a TLSConfig

Ah, yeah I see now. The two aren't intended to be swapped out for each other at all. The `TLSConfig` get used to generate the `crypto/tls.Config` that is assigned to [`config.HttpClient.Transport`](https://github.com/hashicorp/consul/blob/a440433ac832516bb026872f698669122a4789b6/api/api.go#L236). So one is the parent object of the other.

**Comment by mdaur** [comment]
this would be also necessary if you use https for consul. It seems there is no option and no environment variable to configure the CA certificate in case of consul makes use of https instead of http:

2016/09/24 22:52:46 Put https://www.mdaur.mooo.com:443/v1/agent/check/pass/radius01-radius01.mdaur.mooo.com?note=ok: x509: certificate signed by unknown authority
Service not registered, registering...
 2016/09/24 22:52:46 Service registration failed: Put https://www.mdaur.mooo.com:443/v1/agent/service/register: x509: certificate signed by unknown authority
2016/09/24 22:52:46 Check registration failed: Put https://www.mdaur.mooo.com:443/v1/agent/check/register: x509: certificate signed by unknown authority

**Comment by tgross** [comment]
Marking this as a 2.x-compatible enhancement.

**Comment by tniswong** [comment]
When implementing, please be sure this config is reloadable via SIGHUP

**Comment by tgross** [comment]
Going to snag this as part of a batch of post-v3 Consul-related improvements.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/401

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.1.0
