### ISSUE TITLE
Extend template rendering for configuration

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#171]
In https://github.com/joyent/containerpilot/issues/145#issuecomment-218928756 @justenwalker proposed a feature like `consul-template` or `confd` where the environment interpolation we do could have extended functionality.

> With golang templates, I think we can provide a mechanism for looking up app-state information. With a bit of tweaking we could do something like [consul-template](https://github.com/hashicorp/consul-template)

> Possibly we could expose an "env" section in the containerpilot config which is loaded just before running any commands

> Limitation is still that reload will not change the environment or the command.

> I'm unsure if we want to pre-process these template env variables along with the rest of the golang templates we currently support, or after the config is loaded (multi-pass). The latter means they'd have to be escaped or otherwise not the same delimiter that golang uses by default.

**Comment by tgross** [comment]
One of the examples we want here is https://github.com/autopilotpattern/consul/issues/17, which I've run into with etcd as well. I'm wondering whether we could accomplish all the known use cases by exposing some new environment variables based on the container configuration automatically. Similar to how Docker exposes information about `--link` as env vars, we could expose something like `CONTAINERPILOT_<servicename>_IP`

**Comment by tgross** [comment]
An implementation path that might work here is to call [os.Setenv](https://golang.org/pkg/os/#Setenv) right [here where we get the service IP](https://github.com/joyent/containerpilot/blob/85596c4fe9b51bc37c778db6e3a7717282881a7e/services/services.go#L98). I _think_ that'd get the variables exposed everywhere we need them.

We'd just need to agree on a naming convention for those env vars.

**Comment by tgross** [comment]
This specific fix would also eliminate some brittle code in user-defined hooks in [autopilotpattern/couchbase](https://github.com/autopilotpattern/couchbase/blob/f428ed912d9d39142f905b306020fb9a5de3c3f4/bin/manage.sh#L15) and [autopilotpattern/elasticsearch](https://github.com/autopilotpattern/elasticsearch/blob/00abe9e52b3602dc9b7c27cf24f92a412665181c/bin/manage.sh#L62)

**Comment by justenwalker** [comment]
> An implementation path that might work here is to call os.Setenv right [here where we get the service IP](https://github.com/joyent/containerpilot/blob/85596c4fe9b51bc37c778db6e3a7717282881a7e/services/services.go#L98). I think that'd get the variables exposed everywhere we need them.

Seems like this would introduce a side-effect into an otherwise pure function.  It would be preferable if it could be done outside this method.

**Comment by tgross** [comment]
> Seems like this would introduce a side-effect into an otherwise pure function. It would be preferable if it could be done outside this method.

I don't entirely disagree that it's overloading the service configuration, but it's not a pure function either -- we're making calls into the OS for inputs. We could put lift it up outside the service parsing, but we can't lift it all the way to the top of `App.Run` because I want to make sure that we update it when we SIGHUP for new config.

**Comment by tgross** [comment]
Released as https://github.com/joyent/containerpilot/releases/tag/2.2.0

**Comment by tgross** [comment]
Good demonstration of this in https://github.com/autopilotpattern/etcd/pull/1/files
