### ISSUE TITLE
CP needs a mechanism for knowing when the exec'd application is in a suitable state

### ISSUE THREAD

**Issue by papertigers** [joyent/containerpilot#173]
It would be nice if CP had a mechanism for knowing when the application it's wrapping is in a suitable state.  Taking the sales app in https://github.com/autopilotpattern/workshop as an example, we hit a race condition between CP and node.  In some cases CP fires the SIGHUP before node has a chance to finish launching and before node registers its event handler.  Thus killing the container instead of having its intended purpose. 

Initial investigation of this issue can be seen here:  https://smartos.org/bugview/OS-5446

**Comment by tgross** [comment]
ContainerPilot doesn't fire SIGHUP, the user-defined `onChange` behavior does (in that example). The `onChange` behavior is entirely in the hands of the application developer and so they have the responsibility to make sure that their application and `onChange` behavior will play nice together.

I'm going to close this as `usage`/`not-a-bug` but open an issue on the workshop application to make sure we have that covered in that example like we should.
