### ISSUE TITLE
Deprecate special chars in service/backend names

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#177]
Since introducing environment variables  (#171) we put a warning in to discourage using non-alpha-numeric names for services and backends.  In the next major release `3.0.0` this should be removed and cause an error in the config. (See [comment](https://github.com/joyent/containerpilot/pull/172#issuecomment-224012834) )

**Comment by tgross** [comment]
Thanks for opening this one, @justenwalker

**Comment by tgross** [comment]
Merged in https://github.com/joyent/containerpilot/pull/284

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev
