### ISSUE TITLE
Question | How to reload application if a key/value pair changes in consul

### ISSUE THREAD

**Issue by himanshu0503** [joyent/containerpilot#180]
Using `preStart` I can get the latest key/value while starting a service.
Is there a way to determine if a key/value changed and call an `onChange` related to it?
Do `backends` support `onChange` event for `keys`? If so how do I specify them in my containerpilot.json?

**Comment by tgross** [comment]
Backends don't support `onChange` events for keys, only services.

A way to get this behavior might be to run `consul-template` as a task (see discussion in https://github.com/joyent/containerpilot/issues/157) or as a coprocess (see discussion in https://github.com/joyent/containerpilot/issues/175)

**Comment by tgross** [comment]
Going to close this as answered. Feel free to reopen if you have follow-up @himanshu0503
