### ISSUE TITLE
Interface missing/ignored running with overlay weave network

### ISSUE THREAD

**Issue by sra** [joyent/containerpilot#181]
ContainerPilot can't seem to find one of the interfaces so is registering the wrong IP.

This is happening in docker cloud with a weave overlay network. The service interface list is set to `["ethwe","eth0"]` and it is choosing `eth0` always even though `ethwe` interface exists when running `ip addr`. If I remove `eth0` from the interface list CP complains about not finding any interfaces.

Here is an example `containerpilot.json`

```
{
  "consul": "consul:8500",
  "preStart": "/opt/containerpilot/containerconfig.sh",
  "services": [
    {
      "name": "wo",
      "port": 56789,
      "health": "/usr/bin/curl -o /dev/null --fail -s http://localhost:56789",
      "poll": 10,
      "ttl": 25,
      "tags": [ "{{.APPNAME}}"],
      "interfaces": [
        "ethwe",
        "eth0"
      ]
    }
  ],
  "backends": [
  ]
}
```

And the interface list. 
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
12: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:06 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.6/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:6/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever
22: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:c4:d0:37:9f:48 brd ff:ff:ff:ff:ff:ff
    inet 10.7.0.17/16 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::f8c4:d0ff:fe37:9f48/64 scope link
       valid_lft forever preferred_lft forever
```

Notably, if I place the command `ip addr` in the preStart script, it prints output identical to below, but the service gets registered with the `eth0:inet` address. If I remove `eth0` from the interfaces list I sometimes get a message that there are no available interfaces that match or sometimes it works.

Maybe if we could add some debugging logs around the search for interfaces, the sorting and the selection to see if it can be tracked down.

**Comment by tgross** [comment]
That certainly seems wrong. Are you getting any logging like "We had a problem reading information about some network interfaces. If everything works, it is safe to ignore this message. Details: <something>"? [ref](https://github.com/joyent/containerpilot/blob/37b946527b49d95997536cbdc4035cd7cb2735b8/utils/ips.go#L59)

I don't have a good weave setup here. I'm curious if there's a problem with `net.Interfaces` in getting the full list of interfaces. Could you `go run` the program below in one of your containers with the ethwe interface?

```go
package main

import (
	"fmt"
	"net"
)

func main() {
	ifaces, _ := net.Interfaces()
	for _, i := range ifaces {
		fmt.Printf("%+v\n", i)
	}
}
```

If you don't have a decent golang setup I've pushed a container to the Hub which you should be able to fetch via `docker pull 0x74696d/gh181`. Running it will look like this:


```
$ docker run 0x74696d/gh181
{Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback}
{Index:2 MTU:1480 Name:sit0 HardwareAddr: Flags:0}
{Index:3 MTU:1452 Name:ip6tnl0 HardwareAddr: Flags:0}
{Index:4 MTU:1448 Name:ip6gre0 HardwareAddr: Flags:0}
{Index:38 MTU:1500 Name:eth0 HardwareAddr:02:42:ac:11:00:02 Flags:up|broadcast|multicast}
```

**Comment by tgross** [comment]
> or sometimes it works

You know, it occurs to me that if you're only seeing the problem sometimes that I wonder if we're seeing some kind of race between the way that the weave overlay adds the interface to the context of the container and the start of PID1.  You might want to try and run that program I gave you a couple times just to see if there's a difference between runs.

**Comment by sra** [comment]
Hi, I'll give it a run - here is the error btw if just set with the overlay. I throught about the race condition as well but I see the interface in the pre-script.

```
2016/06/17 17:44:50 Unable to parse services: None of the interface specifications were able to match
2016-06-17T17:44:50.682577829Z Specifications: [{ethwe ethwe %!s(bool=false)}]
2016-06-17T17:44:50.682583610Z Interfaces IPs: [eth0:172.17.0.6 eth0:fe80::42:acff:fe11:6 lo:::1 lo:127.0.0.1]
```

**Comment by tgross** [comment]
> I throught about the race condition as well but I see the interface in the pre-script.

The pre-script starts well after we parse the interfaces in ContainerPilot. You'd see the `None of the interface specifications were able to match` error before that.

**Comment by sra** [comment]
I think that must be it - here is the output of the go command:

```
# go build if.go
root@app-missionmode-1:/build# ./if
{Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback}
{Index:50 MTU:9001 Name:eth0 HardwareAddr:02:42:ac:11:00:06 Flags:up|broadcast|multicast}
{Index:52 MTU:1410 Name:ethwe HardwareAddr:5e:6b:c3:59:30:ac Flags:up|broadcast|multicast}
```

If i just run the containerpilot again with an echo after it is booted here is the result which is correct:

```
containerpilot -config file:///opt/containerpilot.json echo {{.CONTAINERPILOT_WO_IP}}
10.7.0.17
```

**Comment by tgross** [comment]
Ok, you might want to report that to the Docker project if you can figure out where to report the problem and get suggestions from them. In the meantime, I'd recommend leaving out the ethwe from your containerpilot.json and then using a preStart to add it back in after you've ensured that the ethwe interface is available. Something like this:

```json
{
  "consul": "consul:8500",
  "preStart": "/opt/containerpilot/containerconfig.sh",
  "services": [
    {
      "name": "wo",
      "port": 56789,
      "health": "/usr/bin/curl -o /dev/null --fail -s http://localhost:56789",
      "poll": 10,
      "ttl": 25,
      "tags": [ "{{.APPNAME}}"],
      "interfaces": [ "eth0" ]
    }
  ],
  "backends": [
  ]
}
```

With a preStart something like (probably needs some tweaking / testing!):

```bash
#!/bin/bash

while true; do
    # check a lock first
    mkdir /tmp/lock || break   
    # if we have a ethwe interface, rewrite the ContainerPilot config and SIGHUP ourselves
    ip addr | grep ethwe \
        && sed -i 's/"eth0"/"ethwe"' /etc/containerpilot.json \
        && kill -SIGHUP 1 \
        && break
    # otherwise wait and retry
    sleep 1
done
```

**Comment by sra** [comment]
I think this will work only the first time the container is started, but if it restarts without being recreated CP will fail before running the script because the config file has been changed to only look for ethwe? I suppose I could add another guaranteed interface lower in the list.

**Comment by tgross** [comment]
Does weave recreate the interface if the container process restarts? I guess you could remove the lock file in the `postStop` or `preStop` but that wouldn't help if the container crashes unexpectedly.

**Comment by justenwalker** [comment]
This is more of a bandaid, but we could add a delay  option to the config to wait a while before running - to give the container time to initialize. Or a delay command that could block until a condition is met.

**Comment by sra** [comment]
Are you certain that the interfaces are read again on a HUP? I'm not finding that the workarounds are working in this case. I've ended up doing a loop like thing but removing eth0 and adding a dummy static: route to get some success.. A delay script might be a really flexible way to solve this class of problems

**Comment by justenwalker** [comment]
Another way to do this is to wrap container pilot by calling a script that delays until your interface is ready. Then use `exec /bin/containerpilot ...` to replace that process as PID1

**Comment by tgross** [comment]
> Are you certain that the interfaces are read again on a HUP?

Pretty sure. We call [`NewApp`]( https://github.com/joyent/containerpilot/blob/37b946527b49d95997536cbdc4035cd7cb2735b8/core/app.go#L261) which calls [`config.ParseConfig`](https://github.com/joyent/containerpilot/blob/37b946527b49d95997536cbdc4035cd7cb2735b8/core/app.go#L91) which calls [`parseServices`](https://github.com/joyent/containerpilot/blob/37b946527b49d95997536cbdc4035cd7cb2735b8/config/config.go#L231) which calls [`services.NewServices`](https://github.com/joyent/containerpilot/blob/37b946527b49d95997536cbdc4035cd7cb2735b8/config/config.go#L101) where we make the call to get the interfaces. I suppose it's possible that golang caches the call... if you modify the test golang program to loop over the call, build it, and then run it as PID1 we'd be able to see if it changes as we expect.

**Comment by tgross** [comment]
@sra were you able to verify the behavior as I described in my last comment?

**Comment by sra** [comment]
I think that it is ok. I stopped using that environment so have not been having the issues anymore.

**Comment by tgross** [comment]
Ok, closing this but it might be a good idea to document this behavior in some "here's some known tricky things" at some point. ref #197

**Comment by tgross** [comment]
This is an old issue but Weave recently published https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix which suggests that getting those interfaces set up is problematic because of network namespace behaviors with M:N in the golang runtime. For visitors from the future, the newer version of Weave that uses multi-processing might fix that.
