### ISSUE TITLE
Documentation: ContainerPilot lifecycle and _why_

### ISSUE THREAD

**Issue by misterbisson** [joyent/containerpilot#197]
https://github.com/joyent/containerpilot/issues/196 highlighted a handful of points that should be more clearly documented:
- The role of user-defined behaviors in the container needs to be better explained. This includes behaviors that will delay application start until the dependent resources are available.
- The lifecycle of containers/applications with ContainerPilot, including what happens before the main process starts, when an application is registered, what happens when health checks fail, and when the application is shut down or unexpectedly stops
- Answer the question: "does ContainerPilot de-register the service before calling `preStop`?"

**Comment by javabean** [comment]
Another point in need of documentation is what happens when a series of Consul changes are fired, and the `onChange` event takes his faire bit of time to execute: will all intermediary events be coalesced into a single one, and will the next `onChange` event firing wait for the previous one to finish? (in other words: does CP manage synchronisation, or must `onChange` handler code takes steps to avoid concurrent application configuration changes?)

**Comment by tgross** [comment]
Some other details we should consider covering:

Signal trapping behaviors, from @javabean in https://github.com/joyent/containerpilot/issues/195#issuecomment-237656899:
> In the meantime, as you previously exposed, and unless we change configuration options, it should be documented that all signals are passed-throu except SIGHUP and SIGUSR1. Let's put this into task #197!

Interactions with late-bound software-defined networking in https://github.com/joyent/containerpilot/issues/181#issuecomment-226840265:
> In the meantime, I'd recommend leaving out the ethwe from your containerpilot.json and then using a preStart to add it back in after you've ensured that the ethwe interface is available.

Emulating wildcard behavior for backends, in https://github.com/joyent/containerpilot/issues/111#issuecomment-198515511
> You can hijack service advertisements to create an artificial group of your applications, and then have your downstream services update based on changes to that service. An onChange handler doesn't receive any information from Containerbuddy as to what backend created the change (unless you pass that in the arguments), so we'll take advantage of that here.

**Comment by misterbisson** [comment]
From https://github.com/joyent/containerpilot/issues/210 we learned of some confusion about the usage of `backends` > `onChange`:

> does the onChange handler not get called on initial startup or containerpilot reload time?

> When the containerpilot process comes up (or reloads), I was assuming that it was going to fire these scripts since "starting" and "reloading" are states in and of themselves.

Corrections were offered in that thread:

> [T]he onChange only gets fired when a monitored backend changes. [...] The `onChange` hooks are associated with the backends, not with the main application.

> [It's supposed] to be called on [changes in a] **monitored** Consul service. For startup routines you can use [the] `preStart` option.

**Comment by tgross** [comment]
Yeah, what's pretty clearly necessary is a step-by-step documentation of the ordering of events. We have this in diagram form in various talks and blog posts but not in a written format in the documentation. The main loop of code is actually very simple but its not reasonable to suggest that end-users read the code.

**Comment by misterbisson** [comment]
From https://github.com/joyent/containerpilot/issues/192#issuecomment-235595932, https://github.com/joyent/containerpilot/issues/205#issuecomment-239528784, and https://github.com/joyent/containerpilot/issues/212: Demonstrate how to use a script to start the main process so that environment variables can be injected into it.

https://github.com/joyent/containerpilot/issues/212#issuecomment-241430996

>[It's] not possible [for a `preStart` script to pass environment variables to the main process] because the `preStart` is a child process of ContainerPilot. There's no way to communicate changes except through the file system.

https://github.com/joyent/containerpilot/issues/205#issuecomment-239535138

>What you'll want to do instead is have ContainerPilot run a script that includes all the environment updates you need and then have that script run your application. So your Dockerfile might include:

>```
CMD ["/usr/local/bin/containerpilot", "/usr/local/bin/start.sh"]
>```

> and then the `start.sh` script will be something like:

>```bash
#!/bin/bash

get_config_data() {
  export KEY=$(/some/val/from/external/source)
  export OTHERKEY=$(/some/val/from/external/source)
}

get_config_data && /usr/local/bin/myApplication
>```

https://github.com/joyent/containerpilot/issues/205#issuecomment-239639740

>your `/start.sh` script should always use `exec` to run the main application - otherwise it will not have any signals propagate:

>*run.sh*:

>```sh
...
get_config_data && exec /usr/local/bin/myApplication
>```

**Comment by misterbisson** [comment]
> Is there a way to have it kill off the container when [the health check fails]?

Another question to answer and offer an example for.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-RC1
