### ISSUE TITLE
Custom SIGN for main app termination

### ISSUE THREAD

**Issue by fitz123** [joyent/containerpilot#208]
Hello!

I wonder, is it possibly to send custom kill signals to main process? Didn't find anything similar in documentation. For example, when I do `docker stop <container_name>`, send to main app SIGNKILL instead of transfer SIGNTERM received from docker?
If you aware of _supervisord_ I'm asking about equivalent of _stopsignal_ option (http://supervisord.org/configuration.html#program-x-section-values). 
My main app have to be terminated with SIGNKILL always

Thank you!

**Comment by tgross** [comment]
I can think of 3 options for you, depending on the behavior you're looking for:
- set a ContainerPilot `stopTimeout` value of `-1`: this fires SIGKILL to the application as soon as any `preStop` hook is complete.
- just use `docker kill` in the first place to send the SIGKILL. ContainerPilot will die w/o performing any more work and its child process will be reaped.
- use [`docker stop -t 1 <container>`]((https://docs.docker.com/engine/reference/commandline/stop/). This will result in ContainerPilot receiving SIGKILL within 1 second of receiving the SIGTERM. ContainerPilot will die w/o performing any more work after 1 second and its child process will be reaped.

**Comment by fitz123** [comment]
Thanks! Not exactly custom signals, but for my needs It works too
