### ISSUE TITLE
ContainerPilot without service discovery

### ISSUE THREAD

**Issue by thoughtarray** [joyent/containerpilot#211]
Great project, really like the pattern.  This project really puts together a lot of other stuff that we had been trying to solve with [S6](https://github.com/just-containers/s6-overlay) such as startup and shutdown behaviors.

It would be nice to use ContainerPilot for the behaviors and _opt out_ of the service discovery bits.  Would this be possible?

**Comment by fitz123** [comment]
You could skip service defining part and it will not try to connect to Service Discovery, but you still have to provide any dumb address for consul, though. I worked for me before

**Comment by tgross** [comment]
This was raised in https://github.com/joyent/containerpilot/issues/117 and has the same configuration option -- simply elide the `services` block and ContainerPilot will never fire health checks and heartbeats to Consul. Or elide the `backends` block if you have no dependencies you care about.

The service catalog option (`consul` or `etcd`, currently) is a required parameter. In fact it's the only required parameter. But if you don't have `services`, `backends`, or `telemetry` blocks then there's never any requests to it.

**Comment by thoughtarray** [comment]
Thanks for the information.  I tried to make sure I wasn't asking a question that was already asked.  I'll play around with it and see how it works.

Aside, I would like to see the consul or etcd options optional.  Or maybe have a noop catalog option.  That way people could use ContainerPilot for behaviors, tasks, and coprocesses without it feeling hacky.

**Comment by tgross** [comment]
If those fields were optional it'd be very easy to have an invalid configuration so we'd have to work out the expected behavior. If you'd like to open an issue w/ a proposal where we could suss out that behavior we could at least discuss it.

Closing this issue as answered.

**Comment by justenwalker** [comment]
@tgross if we added a service discovery option explicitly, we could enforce that Service and Backends are *not* configured and fail if they are.

However, it may be a bit awkward in the config since it's a key and needs a value:

```json
{
  "noop": null
}
```
the null value does not matter here, what matters is the key only.

**Comment by thoughtarray** [comment]
@tgross: I will put something intelligible together soon and open a proposal.

@justenwalker: Yeah, it is kind of awkward.  I thought it was weird that the service catalog option was a top-level key as opposed to a nested dict, but it does make configuration very easy.

```json
{
  "consul": "...",
  ...
}
```
--- vs ---
```json
{
  "service_catalogs": [
    {"type": "consul", "host": "foo:8500"},
    {"type": "zk", "host": "foo:2181", "service_root": "sd/prod/bar-app/"}
  ],
  ...
}
