### ISSUE TITLE
create and export env variables during preStart

### ISSUE THREAD

**Issue by fitz123** [joyent/containerpilot#212]
Hello everyone! 

Have a filling that something is wrong with me, but cannot figure out what is the problem, and how it suppose to work.

I have this: `ENTRYPOINT  ["/usr/local/bin/containerpilot","ffmpeg"]`
And want to generate some options for main app from inside container and run container like this: 
```
docker run -d \
    {{dockeOpts}} \
    containerName \
        {{ffmpegOptions}} \
        '$ENV_VARIABLE_FROM_INSIDE_CONTAINER'
```
I'm trying to generate and `export` variables during preStart routines, but: 
1. I don't actually see any of exported values in the container environment
2. Even if I succeed and find out how to export them properly, will they be applied by containerpilot as part of {{ffmpegOptions}} ?

**Comment by justenwalker** [comment]
I'm not sure exactly what you want to do, but it seems similar to a question received before in #192 
(See [this comment](https://github.com/joyent/containerpilot/issues/192#issuecomment-235595932))

I think what you want to accomplish can be done by using a script rather than ffmpeg directly.

**Comment by fitz123** [comment]
@justenwalker thanks!
Looks like it should work as I need, since I can access everything I need from the script itself. 
Currently I passing a huge amount of options to ffmpeg directly. This way I'll need to pass all that stuff as environment inside container and generate a command by start.sh script.
So The question is: is it the only possibly solution or the best one?

What I'm trying is to `export` a needed variable during preStart, and make an app use this variable by passing its name directly during container creation. Just to confirm it's not possibly and I'll make start.sh =)

**Comment by tgross** [comment]
> What I'm trying is to export a needed variable during preStart, and make an app use this variable by passing its name directly during container creation.

That's not possible because the `preStart` is a child process of ContainerPilot. There's no way to communicate changes except through the file system. See https://github.com/joyent/containerpilot/issues/205 for an in-depth discussion.

**Comment by fitz123** [comment]
Thanks, @tgross, excellent explanation! 
Will subscribe to #205 updates, pretty interesting
