### ISSUE TITLE
Discussion: Discovery service-specific configuration

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#213]
I see some times a lot of consul-specific configuration options come up, and it is met with some trepidation, since ContainerPilot's configs are meant to be agnostic. But there appear to be cases where we cannot ignore the differences between those backends, and users do want to take advantage of those specific features.

I'd like to open this issue to get some ideas thrown around about how we can cope with the dissimilarities between the backends. The goal is to allow us to safely create specific features that may only work for a single backend and design configuration in a way that targets it directly and unambiguously.

Here is one such proposal: **namespaced extensions**

Given our current service configuration object such as the one from the documentation.

``` json
    {
      "name": "app",
      "port": 80,
      "health": [
        "/usr/bin/curl",
        "--fail",
        "-s",
        "http://localhost/app"
        ],
      "interfaces": [
        "eth0",
        "eth1[1]",
        "192.168.0.0/16",
        "2001:db8::/64",
        "eth2:inet",
        "eth2:inet6",
        "inet",
        "inet6"
      ],
      "poll": 10,
      "ttl": 30,
      "timeout": "10s",
      "tags": ["tag1"]
    }
```

If we wanted to take advantage of consul's unique service options; perhaps we could extend this to include a `CheckID` by including a `consul` namespace for those options (see #193)

``` json
{
  "name": "app",
  "port": 80,
  "health": [
    "/usr/bin/curl",
    "--fail",
    "-s",
    "http://localhost/app"
  ],
  "interfaces": [
    "eth0",
    "eth1[1]",
    "192.168.0.0/16",
    "2001:db8::/64",
    "eth2:inet",
    "eth2:inet6",
    "inet",
    "inet6"
  ],
  "poll": 10,
  "ttl": 30,
  "timeout": "10s",
  "tags": ["tag1"],
  "consul": {
    "CheckID": "myservice-check"
  }
}
```

The goal is still to put as much as we can into the root namespace, but also to not be so constrained by the fact that other backends are not entirely compatible.

**Comment by tgross** [comment]
I'm open to the idea but I also wonder whether we have enough use cases to justify the added complexity. Like in the case of #193 having a field that the etcd backend ignores seems easy enough.

That being said, I definitely like the syntax here if we're going to do this; it certainly beats "vendor prefix" type config like having `consul-checkId` or something like that.

**Comment by justenwalker** [comment]
> I also wonder whether we have enough use cases to justify the added complexity.

If we can completely avoid the backend-specific configurations that is preferable, but I feel that it might be unavoidable in the near future - so I think it's good to start thinking about it. We only support etcd and consul, but if we get #214 then zookeeper is adds a third - and balancing the LCD of features could get tricky.

**Comment by tgross** [comment]
Example in https://github.com/joyent/containerpilot/pull/252

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.6.0
