### ISSUE TITLE
Service "Port" is not updated if service exists on the same node

### ISSUE THREAD

**Issue by fitz123** [joyent/containerpilot#215]
Hi everyone!
I have consul agent running in a separate container in every node. All containers are in _host_ network. All containerpilots use localhost as consul address. If container exits not gracefully - service left in critical state. It's fine, since as far as I understand CP have no way to deregister check if it exited forcibly or unexpected. But it leads to the very nasty issue

What's happening:

1. Service with a random generated port was registered on the node
2. Container exited not gracefully and left critical service behind
3. New container with the same service ID, but different port has been created on the same node

Result: service becomes healthy but **service "Port" didn't updated** , value left from previously registered container

**Comment by tgross** [comment]
> All containers are in host network. 

This is not a supported configuration. ContainerPilot requires network virtualization with an IP per container.

**Comment by fitz123** [comment]
Related consul ability: https://github.com/hashicorp/consul/pull/2276

**Comment by fitz123** [comment]
@tgross .

>  This is not a supported configuration

just like that? I'm agree it could be not recommended, but it should be possibly to use it this way. It's not always possibly to use virt networks, specifically for cases where you have: 

* high network usage
* extensive multicast traffic
* network sensitive applications
* unstable host network environments

And this is just my cases, I'm sure there're plenty of other cases where one would use host network

**Comment by fitz123** [comment]
I may think of few workarounds, like:

* Try to deregister service with the same name and node during preStart
* Use predictably ports for a service, so the same service always have same port

But probably there's a better way to fix it

**Comment by tgross** [comment]
The more fundamental problem you're having is not so much deregistration but that you're using host networking for an application but expecting to be able to have random ports on the same IP without coordination between services.

> I may think of few workarounds, like:
> * Try to deregister service with the same name and node during preStart
* Use predictably ports for a service, so the same service always have same port

These seem like decent workarounds. I'd go for the latter myself because otherwise you can only run a single instance of a given service on a given host.

**Comment by fitz123** [comment]
@tgross Thank you for advice! I appreciate it

I see no problem to run 1 instance of a given service on a given node, because the only reason to run second instance in my case is failover or network bandwidth (or different resource contention) and second instance actually should be running on different node. Currently I'm even using swarm affinity rules to achieve this

If there's no better options then mentioned, I'll close this.

Thank you again.
