### ISSUE TITLE
Need node deregistration from Consul cluster when a container exited

### ISSUE THREAD

**Issue by joongyu** [joyent/containerpilot#218]
I'm using containerpilot with consul as backend discovery. The consul agent is running as a coprocess for containerpilot. 

I see that it successfully register its node and service to the consul when it started. But, I found out that containerpilot does not deregisters the node itself from consul cluster when it's terminated while it deregisters its service.  (I've checked this on latest release version of containerpilot 2.4.1)

Is there a reason containerpilot does not deregister its node on consul? 
If not, it seems to leave itself when exited.

**Comment by tgross** [comment]
ContainerPilot doesn't contain any Consul-agent specific behavior for co-processes, so when ContainerPilot receives SIGTERM it leaves the co-processes running until the entire container exits. 

You can use the `postStop` hooks to cause the agent to [leave the cluster gracefully](https://www.consul.io/docs/commands/leave.html). Your configuration might something look like this:

```json
{
  "consul": "localhost:8500",
  "coprocesses": [
    {
      "command": ["/usr/local/bin/consul", "agent",
                  "-data-dir=/var/lib/consul",
                  "-config-dir=/etc/consul",
                  "-rejoin",
                  "-retry-join", "{{ .CONSUL }}",
                  "-retry-max", "10",
                  "-retry-interval", "10s"],
      "restarts": "unlimited"
    }
  ],
  "postStop": "consul leave"
}
```

Note that the `postStop` will not fire if the underlying compute host crashes, so you can still end up with stale Consul agents in that scenario.

**Comment by fitz123** [comment]
@joongyu You can use consul option "leave_on_terminate" for this.

https://www.consul.io/docs/agent/options.html#leave_on_terminate

**Comment by joongyu** [comment]
@tgross I'm using postStop in order to leave from consul. I thought conatinerpilot does something regarding node registration. Now I see it doesn't :) Thanks.
@fitz123 Good to know that such option exists!. I should try this.

**Comment by misterbisson** [comment]
Thanks for the tip @fitz123. I opened https://github.com/autopilotpattern/nginx/issues/27 to implement `leave_on_terminate` in that repo and others.

**Comment by fitz123** [comment]
@misterbisson, @joongyu additional info that could be helpful is [DeregisterCriticalServiceAfter](https://www.consul.io/docs/agent/http/agent.html#agent_check_register) option, implemented in Consul v0.7. It'll help with dead services which I'm having a lot in Docker Swarm cluster environment with unstable networking.
That's one of the mayor reasons I'm really looking forward for 0.7 release, and hope you'll be able to implement this in containerpilot

**Comment by tgross** [comment]
From https://github.com/joyent/containerpilot/issues/220#issuecomment-247407535
> If we do so we'll be pinning all use of Consul to 0.7 or above. I think we can do that but we'll need to do some testing of course.

I think this is worth taking a look at.

**Comment by tgross** [comment]
For this, we'll add the `DeregisterCriticalServiceAfter` flag to our call to [`AgentServiceCheck`](https://godoc.org/github.com/hashicorp/consul/api#AgentServiceCheck) that happens in the [`registerCheck`](https://github.com/joyent/containerpilot/blob/4d2c335457cc0e9de7b2ea37f8903877029269b9/discovery/consul/consul.go#L133-L143) method for Consul.

We'll need newer Consul bindings than we have currently though, so this will have to wait slightly until the first part of https://github.com/joyent/containerpilot/issues/243 is done (cc @flyinprogrammer as an FYI).

**Comment by flyinprogrammer** [comment]
Here's a PR to test using consul ~0.7.0 https://github.com/joyent/containerpilot/pull/248

**Comment by flyinprogrammer** [comment]
Would we like to use https://github.com/joyent/containerpilot/issues/213 to tackle the `DeregisterCriticalServiceAfter` flag state?

**Comment by tgross** [comment]
@flyinprogrammer yeah that's probably a good idea and will be a good demonstration of that proposal.

**Comment by tgross** [comment]
Being implemented in https://github.com/joyent/containerpilot/pull/252

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.6.0
