### ISSUE TITLE
Deregister left/old services

### ISSUE THREAD

**Issue by fitz123** [joyent/containerpilot#220]
Is it possibly to implement [DeregisterCriticalServiceAfter](https://www.consul.io/docs/agent/http/agent.html#agent_service_register) option?

I think it's related to #200

**Comment by tgross** [comment]
If we do so we'll be pinning all use of Consul to 0.7 or above. I think we can do that but we'll need to do some testing of course.

**Comment by tgross** [comment]
I'm going to close this as a dupe of https://github.com/joyent/containerpilot/issues/218 though
