### ISSUE TITLE
Health check not honoring exit code

### ISSUE THREAD

**Issue by nickwales** [joyent/containerpilot#223]
Creation of health check and service is working fine, but health check status doesn't update when my health endpoint returns non 200 status codes. The health endpoint is powered with a simple webrick server, the response looks similar to this.

```
  response.status = 500
  response.content_type = 'text/plain'
  response.body = "Something is wrong"
```

With CP DEBUG turned on I can see the health checks happening and then the associated webrick access log event, so I can tell it is configured OK.

A response of 500 from the health endpoint gives the curl command `curl --fail -s http://localhost:8008/alive.txt` (I'm running with `--net=host`) an exit code of 22 but CP continues to send passing health checks to consul.

I've been using CP version 2.4.1 and 2.4.2 since yesterday.

**Comment by tgross** [comment]
Just for clarification, is this a new issue with 2.4.2 or were you seeing this with 2.4.1 as well?

**Comment by nickwales** [comment]
I'm seeing this with both versions. 


This is the services portion of the config file I'm using, might be useful!
```
 "services": [
    {
      "name": "service-name",
      "port": 8080,
      "health": "/usr/bin/curl --fail -s --show-error --output /dev/null http://0.0.0.0:8080/alive.txt",
      "interfaces": [
        "eth0",
        "eth1[1]",
        "192.168.0.0/16",
        "2001:db8::/64",
        "eth2:inet",
        "eth2:inet6",
        "inet",
        "inet6"
      ],
      "poll": 10,
      "ttl": 30,
      "timeout": "10s",
      "tags": ["tag1"]
    }
  ]
```

**Comment by tgross** [comment]
Ok I was able to confirm this behavior with another container image running 2.4.2 and 2.4.1. Sorry about that -- that's obviously a serious bug and I'm not sure how it made past the test suite but we'll make it right.

I'm in the process of trying to determine what version the problem appeared in so I can fix it ASAP.

**Comment by nickwales** [comment]
Thanks for the quick response! Looking forward to 2.4.3

**Comment by tgross** [comment]
Adding the following failing test to `commands_test.go` demonstrates out the behavior:

```go
func TestRunWithTimeoutFailed(t *testing.T) {
	log.SetLevel(log.DebugLevel) // DEBUG
	cmd, _ := NewCommand("./testdata/test.sh failStuff --debug", "0")
	fields := log.Fields{"process": "test"}
	if err := RunWithTimeout(cmd, fields); err == nil {
		t.Errorf("Expected error but got nil")
	}
}
```

Currently this will give us:

```
=== RUN   TestRunWithTimeoutFailed
time="2016-09-29T20:47:55Z" level=debug msg="./testdata/test.sh.RunWithTimeout start"
time="2016-09-29T20:47:55Z" level=debug msg="./testdata/test.sh.Cmd.Start"
time="2016-09-29T20:47:55Z" level=debug msg="./testdata/test.sh.run waiting for PID 461: "
time="2016-09-29T20:47:55Z" level=info msg="Running failStuff with args: --debug" process=test
time="2016-09-29T20:47:55Z" level=debug msg="./testdata/test.sh.run complete"
time="2016-09-29T20:47:55Z" level=debug msg="./testdata/test.sh.RunWithTimeout end"
--- FAIL: TestRunWithTimeoutFailed (0.01s)
        commands_test.go:85: Expected error but got nil
```

The relevant code section is here: 

```
	if _, err := cmd.Process.Wait(); err != nil {
		if err.Error() == errNoChild {
			log.Debugf(err.Error())
			return nil // process exited cleanly before we hit wait4
		}
		log.Errorf("%s exited with error: %v", c.Name, err)
		return err
	}
```

We're assuming that [`Process.Wait()`](https://golang.org/pkg/os/#Process.Wait) returns an error if the process exits with an error code. [`Cmd.Wait()`](https://golang.org/pkg/os/exec/#Cmd) returns with an error value on a non-zero exit code but `Process.Wait()` returns an error on OS-specific details (like if the process isn't a child process) and instead we should be checking the value of the `ProcessState.Success()` method.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/224 with the fix.

**Comment by tgross** [comment]
Released as https://github.com/joyent/containerpilot/releases/tag/2.4.3

**Comment by tgross** [comment]
@nickwales I've been able to confirm that we're respecting exit codes on the same test case I used earlier. Can you double-check at your end too?

**Comment by nickwales** [comment]
@tgross LGTM I am able to make checks pass and fail as expected now. 

Thanks for turning that around so quickly!

**Comment by nickwales** [comment]
@tgross were you able to determine which version introduced the bug? We've got various versions running so would be great to know.

**Comment by tgross** [comment]
Yeah, it was introduced in 2.4.0. From the PR:

> It looks like this got introduced to most of the pollables during the refactoring to support timeouts for health checks (#184);
