### ISSUE TITLE
syntax highlighting renders strangely, readability suffers

### ISSUE THREAD

**Issue by numericillustration** [joyent/containerpilot#228]
on IRC in #joyent bsmithx10 reported that https://www.joyent.com/containerpilot/docs/installation has some syntax highlighting rendering issues causing the readability to be sub-optimal.

**Comment by tgross** [comment]
@numericillustration thanks for the report. Looks like this is the troublesome spot:

![screen shot 2016-10-11 at 3 21 34 pm](https://cloud.githubusercontent.com/assets/1409219/19285030/73f7957a-8fc6-11e6-9ac9-be1e8cfbcf72.png)

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/239.

**Comment by tgross** [comment]
Merged https://github.com/joyent/containerpilot/pull/239 and now awaiting release to the site

**Comment by tgross** [comment]
Released by @fitzage and looking good on https://www.joyent.com/containerpilot/docs/installation. Closing!
