### ISSUE TITLE
CONTAINERPILOT_* environment variables for hook scripts

### ISSUE THREAD

**Issue by jasonpincin** [joyent/containerpilot#229]
Proposing that ContainerPilot set certain environment variables (prefixed by CONTAINERPILOT_) that are accessible by all hook scripts, tasks, co-processes, and the "main" application process.. 
### List of environment variables
- `CONTAINERPILOT_PID` - The PID of ContainerPilot itself, useful for signaling it to reload it's own config
- `CONTAINERPILOT_APP_PID` - The PID of the primary application 

That's all I have for now. There may be other valuable pieces of information now or later that can follow the same naming scheme. 

See #232 for a related proposal.

**Comment by tgross** [comment]
> The PID of ContainerPilot itself

Isn't that always 1?

**Comment by misterbisson** [comment]
> > The PID of ContainerPilot itself

> Isn't that always 1?

What if ContainerPilot is being run via another supervisor/init system, as we've suggested for use in VMs or infrastructure containers?

**Comment by tgross** [comment]
Ah, fair enough I'd forgotten that use case. Totally trivial to get with `os.Getpid()` too.

**Comment by jasonpincin** [comment]
Updated description to mention #232, and asset that the env vars would be exported for tasks, co-processes, and the main application (instead of just hook scripts as I originally implied).

**Comment by tgross** [comment]
Marking this as a 2.x-compatible enhancement.

**Comment by tgross** [comment]
So looking into this a bit, getting the `CONTAINERPILOT_PID` into the environment will be trivial. We can do this right before we load the config via `os.Setenv("CONTAINERPILOT_PID", os.Getpid())`

Getting the `CONTAINERPILOT_APP_PID` is trickier though. Currently for the main app in `RunAndWait` we do a `exec.Cmd.Run()` which blocks until exit, so we don't have a way of getting at the process PID. We can change this to `exec.Cmd.Start()`, get the PID, and then do `exec.Cmd.Process.Wait()`. We do this in the pollables now, but its racy in terms of getting errors on the PID and Wait if the command exits quickly (i.e. it crashes). This should be less of a problem with the main app.

We also use this section for the other hooks that are running exclusively: `preStart`, `preStop`, and `postStop`. We could reduce special casing and also expose a `CONTAINERPILOT_PRESTART_PID`, `CONTAINERPILOT_PRESTOP_PID` and `CONTAINERPILOT_POSTSTOP_PID` variable if we construct the env var name from the name of whatever `Command` struct we're running.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/250 for this.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.5.0
