### ISSUE TITLE
Put Help Wanted in Up-For-Grabs.net

### ISSUE THREAD

**Issue by justenwalker** [joyent/containerpilot#230]
I was informed of a site called [Up For Grabs](http://up-for-grabs.net/) that allows maintainers to register open issues for people who want to get started contributing to open source projects, but don't know where to start.

From the site:

>  What sort of tasks are a good fit?
> - Tasks should take no longer than a few nights' worth of work
> - Tasks should stand alone - avoid core functionality on which other tasks depend
> - Tasks should be well described with pointers to help the implementer
> 
> We suggest the tag `up-for-grabs` but using a different name is also acceptable.
> 
> If this sounds like you, getting involved is simple:
> - Tag bugs and feature requests that would be a good place to start
> - Grab the URL to this list of tasks so that others can get to it easily
> - [Sign in to GitHub](https://github.com/login) and check out the [README](https://github.com/up-for-grabs/up-for-grabs.net#add-your-project).

Since these issues are already labeled, It wouldn't be too much work to get them added to this public list, if there is some interest in it.

**Comment by tgross** [comment]
I like this idea. "Good first bug" or "up for grabs" was totally what I was going for with the "help wanted" label too.

**Comment by tgross** [comment]
I'd like to expand the CONTRIBUTING.md a bit before we do this. I'll try to put up a PR for that in the next day or two.

**Comment by tgross** [comment]
I'm going to be working on a bunch of major enhancements over the next few weeks so I'm going to hold off on doing this until after we've settled back down after the 3.x release so that we're not throwing new people into the code base just as its making major changes.

**Comment by salaxander** [comment]
Just wanted to throw a +1 on this. Seems like it would be really great to help people get started contributing!

**Comment by tgross** [comment]
PR opened: https://github.com/up-for-grabs/up-for-grabs.net/pull/635

**Comment by tgross** [comment]
And merged!
