### ISSUE TITLE
Exposure of 'CONTAINERPILOT_<SERVICE>_IP' variable in management lifecycle

### ISSUE THREAD

**Issue by cmacrae** [joyent/containerpilot#242]
As per the documentation, I'd been wanting to use the `CONTAINERPILOT_<SERVICE>_IP` variable in the early stage of a container's lifecycle -- specifically, in the `preStart` stage.  

Whilst testing, it doesn't seem this variable is exposed this early on. I'm just wondering if this is a design choice, or a limitation (perhaps impossible to expose, as the container doesn't even have any interfaces up when `preStart` is called?)?

Right now, I'm having to use a workaround, in which I render some templates from my `startUp` function in my script, which is what's being executed by ContainerPilot to start the container's service. To better explain this, here's an example of my `containerpilot.json`:
``` json
{
    "consul": "{{.CONSUL}}:8500",
    "preStart": "/usr/local/bin/kafkaManage.sh preStart",
    "logging": {
	"level": "INFO",
	"format": "default",
	"output": "stdout"
    },
    "stopTimeout": 5,
    "preStop": "/usr/local/bin/kafkaManage.sh preStop",
    "postStop": "/usr/local/bin/kafkaManage.sh postStop",
    "services": [
	{
	    "name": "kafka",
	    "port": 9092,
	    "health": ["/usr/local/bin/health.sh"],
	    "interfaces": ["eth0"],
	    "poll": 10,
	    "ttl": 30,
	    "timeout": "10s",
	    "tags": ["kafka", "streaming"]
	}
    ],
    "backends": [
	{
	    "name": "zookeeper",
	    "poll": 30,
	    "timeout": "30s",
	    "onChange": "/usr/local/bin/kafkaManage.sh onChange"
	}
    ]
}
```

Then, here are the relevant portions of my `kafkaManage.sh` script:
``` bash
#! /usr/bin/env bash

# Runs before the shimmed process
preStart(){
    echo "No preStart actions"
}

startUp() {
    # Expose the container IP address
    if [[ $1 == '-a' && -n $2 ]]; then
	export CONTAINER_IP=$2
    fi

    echo "CONTAINER_IP configured as: ${CONTAINER_IP}"
    writeHealthCheck &
    configure && /usr/local/bin/createTopics.sh &
    $KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties
}

configure() {
    echo "Configuring createTopics.sh"
    # Configure the createTopics script
    consul-template \
	-once \
	-dedup \
	-consul ${CONSUL}:8500 \
	-template "/etc/createTopics.sh.ctmpl:/usr/local/bin/createTopics.sh"

    chmod 755 /usr/local/bin/createTopics.sh

    echo "Configuring Kafka server.properties"
    # Configure the main Kafka properties
    consul-template \
	-once \
	-dedup \
	-consul ${CONSUL}:8500 \
	-template "/etc/kafka_properties.ctmpl:${KAFKA_HOME}/config/server.properties"

}

echo "Running: $@"
$@
```

And, lastly, here's the `CMD` I'm using in my Dockerfile so you can see how I'm exposing the container's IP as an argument to the script:
```
CMD ["/usr/local/bin/containerpilot","/usr/local/bin/kafkaManage.sh","startUp","-a","{{.CONTAINERPILOT_KAFKA_IP}}"]
```

This works fine, but it'd be nice to run the `consul-template` steps with the `{{.CONTAINERPILOT_KAFKA_IP}}` available in the `preStart` function.

**Comment by fitz123** [comment]
let me ask, how do you know private container's IP before container creation?

**Comment by cmacrae** [comment]
@fitz123 Perhaps you missed this specific part of my question:
> I'm just wondering if this is a design choice, or a limitation (perhaps impossible to expose, as the container doesn't even have any interfaces up when preStart is called?)?

Also, pretty sure the container has definitely been created, considering it has to before the ContainerPilot runtime executes.
Perhaps you mean before the container has a chance to get an IP? In which case, see my first point

**Comment by tgross** [comment]
> Whilst testing, it doesn't seem this variable is exposed this early on. 

If you take a look at https://github.com/joyent/containerpilot/pull/172/files we're creating the `CONTAINERPILOT_<SERVICE>_IP` when we parse the application configuration into the ContainerPilot state. In `main.go` you can see we do the `NewApp`->`LoadApp` before we run the application, so that environment variable should definitely be available to all user hooks.

Do you have an example configuration and Dockerfile that shows what you're seeing?

---

```
CMD ["/usr/local/bin/containerpilot","/usr/local/bin/kafkaManage.sh","startUp","-a","{{.CONTAINERPILOT_KAFKA_IP}}"]
```

This can't work, as @fitz123 is getting at, because the command line is evaluated before the container is started. In which case, ContainerPilot itself hasn't started and can't therefore render out the config variable. That template config won't be rendered by whatever is starting your container either.

**Comment by fitz123** [comment]
@cmacrae
you can always call any of shell things to get IP address during preStart. For example:
```
  "preStart": "getip.sh",
...

cat getip.sh 
#!/bin/bash
ip route get 1 | awk '{print $NF;exit}'
```

**Comment by cmacrae** [comment]
@tgross I think there's been a bit of miscommunication here.
> `CMD ["/usr/local/bin/containerpilot","/usr/local/bin/kafkaManage.sh","startUp","-a","{{.CONTAINERPILOT_KAFKA_IP}}"]`
This can't work, as @fitz123 is getting at, because the command line is evaluated before the container is started. In which case, ContainerPilot itself hasn't started and can't therefore render out the config variable. That template config won't be rendered by whatever is starting your container either.

This does work - it's what I'm using as my workaround. This works both within the Dockerfile or if I configure a `command` block in my `docker-compose.yml`.

**Comment by cmacrae** [comment]
@fitz123 Yep, thanks for the suggestion. I've used this method previously -- I just wanted to open this issue and ask the question to see if there was a more elegant approach

**Comment by fitz123** [comment]
`CMD [ "/usr/local/bin/containerpilot","echo","{{.CONTAINERPILOT_TEST_IP}}"]`

Confirmed, this actually and surprisingly works too! =)

**Comment by tgross** [comment]
D'oh you're right! [How embarassing!](https://github.com/joyent/containerpilot/blame/bad44bd445806614d91f1746a9722d88a043a8db/core/app.go#L180) 😊 

Ok, so that being said you should still have `CONTAINERPILOT_KAFKA_IP` at `preStart`.

> I'm just wondering if this is a design choice, or a limitation (perhaps impossible to expose, as the container doesn't even have any interfaces up when preStart is called?)?

Are you using something like Weave where the interfaces are created by an external application? (ref https://github.com/joyent/containerpilot/issues/181)

**Comment by cmacrae** [comment]
Ah! Well at least we know now 👍 

Okay, great, that's good to hear.
So I could have a value for preStart of something like: `/usr/local/bin/kafkaManage.sh preStart -a {{.CONTAINERPILOT_IP}}`? I believe I tried this, and it kept coming up empty, but that could've been due to some bum scripting (its been a long day!).

>Are you using something like Weave where the interfaces are created by an external application? (ref #181)
Well, right now I'm just trying to make sure this runs in my dev environment, using Docker Compose.

**Comment by fitz123** [comment]
Ok, I got this _issue_

As [documentation said](https://www.joyent.com/containerpilot/docs/configuration) 

> The CONTAINERPILOT_{SERVICE_NAME}_IP environment variable that is set by the services configuration is available to the command arguments but not to the configuration file.

So I didn't get it work directly as {{.CONTAINERPILOT_TEST_IP}} value in the containerpilot.json -> preStart, but you still can get it there via scripts:


```
"preStart": "showip.sh",
```
```
cat showip.sh
#!/bin/bash
echo "${CONTAINERPILOT_TEST_IP}"
```

This I guess only @tgross can comment, and for me it looks like some technical limitation and chicken-egg situation.

**Comment by cmacrae** [comment]
@fitz123 Oh, nice! Thanks for reporting back with that. I had some problems accessing it directly in scripts, hence why I ended up exposing it as an argument. I'll have to give that a shot tomorrow :)

**Comment by tgross** [comment]
> Ok, I got this issue

> This I guess only @tgross can comment, and for me it looks like some technical limitation and chicken-egg situation. I think CP evaluates all variables before start and there no such variable exists yer. But when we're accessing the variable from preStart -> bash, it executes after CP initialization and at this time we already have it propagated into env

Yeah you've got it now.

The `CONTAINERPILOT_<SERVICE>_IP` can't exist until after we've read the configuration file because:

1. we get the `<SERVICE>` portion of the key name from the `name` key in the `services` block
2. we get the interface for the IP from the `interfaces` key in the `services` block 

So in order to support having `CONTAINERPILOT_<SERVICE>_IP` in the ContainerPilot config itself we would have to do two passes on the rendering of the configuration file. So you can use the environment variable in the various hooks but not within the configuration itself.

**Comment by cmacrae** [comment]
Awesome. Glad to have a better understanding of it now. I was only trying to use the var directly as I couldn't seem to simply use `$CONTAINERPILOT_<SERVICE>_IP` in a shell script successfully. But I'm sure that was down to some mistake I was making :)

I'll have a play with this tomorrow 👍🏻

**Comment by cmacrae** [comment]
Okay, great - it works with just using `CONTAINERPILOT_<SERVICE>_IP` in scripts called from `preStart`. Not sure what exactly I was doing to get in the way of this behaviour yesterday 🤔 

Thanks for the discussion on this @fitz123 @tgross 👍 

I'll close this off :)
