### ISSUE TITLE
Support Consul EnableTagOverride

### ISSUE THREAD

**Issue by flyinprogrammer** [joyent/containerpilot#243]
If I'm reading this correctly:
https://github.com/joyent/containerpilot/blob/master/glide.yaml#L24
It means we're using consul from this commit:
https://github.com/hashicorp/consul/tree/158eabdd6f2408067c1d7656fa10e49434f96480

Which means we're using consul bindings from 0.5.2
There have been a lot of updates since then (we're on 0.7.1 now), like `EnableTagOverride`
https://github.com/hashicorp/consul/blob/73b281a27c748210f64e4e83b23312d23afb4593/api/agent.go#L51

And I was hoping to add an option to use `EnableTagOverride` here:
https://github.com/joyent/containerpilot/blob/master/discovery/consul/consul.go#L127

Which would mean probably adding a field to the `ServiceDefinition`?
https://github.com/joyent/containerpilot/blob/master/discovery/discovery.go#L22
But I'm hesitant to do that because things like `etcd` have no concept of an `EnableTagOverride` flag. So I just don't know how we want to accomplish this.

I'm sorry I'm so new to this code base. I demand :stuck_out_tongue: that I write the code and submit the patch, if this is a feature we want? (I need it.), so I would appreciate any and all feedback so I can start contributing more silly ideas.

**Comment by tgross** [comment]
There's no specific reason we've fallen behind on that, so updating the bindings sounds like a good idea. What would `EnableTagOverride` look like in the case where we have non-Consul backends?

Just for the record, because I had to look up what that does (from https://www.consul.io/docs/agent/services.html):

> The enableTagOverride can optionally be specified to disable the anti-entropy feature for this service. If enableTagOverride is set to TRUE then external agents can update this service in the catalog and modify the tags. Subsequent local sync operations by this agent will ignore the updated tags.

**Comment by tgross** [comment]
@flyinprogrammer I'd like to suggest that you make two PRs if you decide to take this on: one to upgrade Consul and a second one to tackle the question of `EnableTagOverride`

**Comment by tgross** [comment]
For `EnableTagOverride` I'm going to suggest you go with the proposal in https://github.com/joyent/containerpilot/issues/213 in terms of config syntax. i.e. namespace the configuration change.

**Comment by tgross** [comment]
Being implemented in https://github.com/joyent/containerpilot/pull/252

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.6.0
