### ISSUE TITLE
HTTP control plane

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#244]
There are a number of cases where we've wanted for lifecycle hooks to be able to communicate information back to ContainerPilot, or to be otherwise able to alter the ContainerPilot environment for purposes of future handler events or the main application itself. Additionally, it's likely that we at Joyent will want the [RFD36](https://github.com/joyent/rfd/blob/master/rfd/0036/README.md) scheduler for Triton to be able to have an interface to communicate with containers, for which we can provide an example in ContainerPilot. This would also make the construction of telemetry sensors less complex and provide us a way to avoid capturing POSIX signals for some operations.

This will give us an answer to the following open issues:
- Allow `preStart` to set environment variables for app & hooks https://github.com/joyent/containerpilot/issues/205 (cc @BobDickinson)
- Pass signals to the main process https://github.com/joyent/containerpilot/issues/195 (cc @javabean)
- Expose ContainerPilot state and configuration through telemetry interface https://github.com/joyent/containerpilot/issues/154

This proposal is to create an HTTP server for ContainerPilot that will typically listen on a socket at `/var/containerpilot.sock` inside a running container. The socket will speak HTTP. In a future minor version update we might consider exposing this socket as a TCP socket, but I'd discourage this because then we can't rely on simple Unix file permissions. The socket will speak a simple HTTP REST protocol.

---

### **`PutEnviron POST /v3/environ`**

This API allows a hook to update the environment variables that ContainerPilot provides to lifecycle hooks. The body of the POST must be in JSON format. The keys will be used as the environment variable to set, and the values will be the values to set for those environment variables. The environment variables take effect for all future lifecycle hooks. The environment variable update will also affect the main application if the update occurs during the `preStart` hook. This API returns HTTP400 if the the key is not a valid environment variable name.

*Example Request*

```
curl -XPOST \
    -d '{"ENV1": "value1", "ENV2": "value2"}' \
    --unix-socket /var/containerpilot.sock \
    http:/v3/environ
```

*Example Response*

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 130
```

---

### **`PutMetric POST /v3/metric`**

This API allows a sensor hook to update Prometheus metrics. (This allows sensor hooks to do so without having to suppress their own logging, which is required under 2.x.) The body of the POST must be in JSON format. The keys will be used as the metric names to update, and the values will be the values to set/add for those metrics. The API will return HTTP400 if the metric is not one that ContainerPilot is configuring.

*Example Request*

```
curl -XPOST \
    -d '{"my_counter_metric": 2, "my_gauge_metric": 42.42}' \
    --unix-socket /var/containerpilot.sock \
    http:/v3/environ
```

*Example Response*

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 65
```

---

### **`Reload POST /v3/reload`**

This API allows a hook to force ContainerPilot to reload its configuration from file. This replaces the SIGHUP handler from 2.x and behaves identically: all pollables are stopped, the configuration file is reloaded, and the pollables are restarted without interfering with the main application.

*Example Request*

```
curl -XPOST \
    --unix-socket /var/containerpilot.sock \
    http:/v3/reload
```

*Example Response*

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 65
```

---

### **`MaintenanceMode POST /v3/maintenance`**

This API allows a hook to force ContainerPilot to go into maintenance mode. This replaces the SIGUSR1 handler from 2.x and behaves identically: all health checks are stopped and the discovery backend is sent a message to deregister the services.

*Example Request*

```
curl -XPOST \
    --unix-socket /var/containerpilot.sock \
    http:/v3/maintenance
```

*Example Response*

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 65
```

**Comment by tgross** [comment]
Ref https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md for the current thinking on this. @cheapRoc has volunteered in https://github.com/joyent/containerpilot/issues/283#issuecomment-282918461 to try to tackle this issue.

**Comment by cheapRoc** [comment]
Ref #300

**Comment by cheapRoc** [comment]
Just to be ultra clear, the `curl` command I'm using is as follows...

```
$ curl -X POST \
    -d '{"ENV1": "value1", "ENV2": "value2"}' \
    --unix-socket /var/containerpilot.sock \
    http://cp/v3/environ
```

...host `cp` is required in `http://cp/v3/environ` but it can be anything and isn't used internally.

**Comment by tgross** [comment]
Sounds good. For some reason I thought you could elide the hostname in the case of a socket but I guess not.

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3
