### ISSUE TITLE
Allow multiple commands for preStart

### ISSUE THREAD

**Issue by rchrd** [joyent/containerpilot#253]
I have some images that require multiple actions before starting the main program. So it would be very useful to be able to specify an array of preStart commands.

**Comment by tgross** [comment]
You can currently do this with a single `preStart` by putting multiple operations within the `preStart` command (for example, use a bash script as your `preStart`).

That being said, in https://github.com/joyent/containerpilot/issues/236#issuecomment-261375257 I've got a configuration change proposal that might be able to do this sort of thing. I'm going to mark this issue as a proposal until that's resolved.

**Comment by tgross** [comment]
We'll be handling this via the work in the [RFD](https://github.com/joyent/rfd/pull/13), in particular the events described under [multiprocess dependency management](https://github.com/joyent/rfd/blob/4b6c69b42cf6833f177826d9a30e14c6ad5cb42c/rfd/0086/multiprocess.md#dependency-management)
