### ISSUE TITLE
Define split function for use in containerpilot.json template?

### ISSUE THREAD

**Issue by deitch** [joyent/containerpilot#261]
Any plans to add `split` to the `FuncMap` passed to the templates in https://github.com/joyent/containerpilot/blob/bad44bd445806614d91f1746a9722d88a043a8db/config/template.go#L48 ?

Very useful for converting strings (e.g. from env vars) to slices, which can then be used for `range` to iterate over actions.

**Comment by tgross** [comment]
There aren't any plans to do so, but I'm not sure I understand how that would look in practice. Particularly because it sounds like the sort of thing that would break backwards compatibility (any env var w/ a `,` in it would now become an array, right?). Can you provide a code/template example here?

**Comment by deitch** [comment]
> Particularly because it sounds like the sort of thing that would break backwards compatibility (any env var w/ a , in it would now become an array, right?)

Nope, not at all. Here is how it works:

```
{{ .SOMEVAR }}
```

The above returns the value of `$SOMEVAR` as a string, while:

```
{{ .SOMEVAR | split " " }}
```

returns a slice of strings, by splitting `$SOMEVAR` on space (or you could do `{{ .SOMEVAR | split "," }}` if you prefer commas, etc.

This in turn lets you iterate over values, e.g.:

```
{{ range $i := .SOMEVAR | split " " }}
// do stuff with $i
{{ end }}
```

Of course, with pure consul templates, that would be:

```
{{ range $i := env "SOMEVAR" }}
```

but containerpilot template already interpolates `.SOMEVAR` with `{{ env "SOMEVAR" }}`

**Comment by tgross** [comment]
Ok, that all seems reasonable then. I'll mark this as an enhancement. Can you think of any other string-munging functions we should add to the template processing step?

And we would certainly welcome a PR if you feel like taking a crack at it!

**Comment by deitch** [comment]
> Can you think of any other string-munging functions we should add to the template processing step?

Hmm, in addition to `split`, the inverse `join` makes sense. It may also make sense to have some form of `replace` and basic regex.

Consul template provides the following key ones: `split`, `join`, `regexMatch`, `replaceAll`, `regexReplaceAll`. Most of those are taken from pkg `regexp`, and not `strings`.

> And we would certainly welcome a PR if you feel like taking a crack at it!
I will try to find some time, but client work piling up. I did just contribute https://github.com/deitch/gopiloted ; is that my good deed for the day? :-)

**Comment by tgross** [comment]
Merged https://github.com/joyent/containerpilot/pull/265. Thanks @deitch! Marking this as "awaiting release" which will be in the next roll-up of small PRs (sometime this week)

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.6.1
