### ISSUE TITLE
running with no child command results in panic

### ISSUE THREAD

**Issue by misterbisson** [joyent/containerpilot#262]
Previously we ran ContainerPilot (was Containerbuddy at the time) without specifying a "main" or child process so we could use it's orchestration capabilities to interact with outside services. 

See https://github.com/autopilotpattern/cloudflare/blob/master/example/docker-compose.yml#L39-L41 and the larger blueprint.

That doesn't seem to work anymore. Here's how that works now:

```
$ containerpilot
2016/12/16 15:31:00 Unable to parse command arguments: received zero-length argument
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45f1c7]

goroutine 1 [running]:
panic(0xb51260, 0xc82000a090)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/joyent/containerpilot/core.(*App).Run(0xc8200802a0)
	/cp/src/github.com/joyent/containerpilot/core/app.go:139 +0x227
main.main()
	/cp/src/github.com/joyent/containerpilot/main.go:25 +0xf1
root@1ae39f4f2ed0:/# 
```

**Comment by tgross** [comment]
We should be allowing for a `nil` command [here](https://github.com/joyent/containerpilot/blob/348b2544c8eb7a4edb234665a0cace0da6b0262e/core/app.go#L154) so that should definitely be working and not panicking. Just took a look thru and I'm not seeing the code path that would cause that off the top of my head but I'll investigate.

**Comment by tgross** [comment]
Ok, I've got a minimum replicable case here.

containerpilot.json:
```json
{
  "consul": "consul:8500"
}
```

docker-compose.yml
```yml
test:
  build: .
  command: >
    /usr/local/bin/containerpilot
  links:
    - consul:consul

consul:
  image: consul:0.7.1
  command: >
    agent -server -client=0.0.0.0 -bootstrap -ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
```

Dockerfile
```
FROM alpine:3.4
RUN apk update && apk add curl
ENV CONTAINERPILOT file://containerpilot.json
RUN curl -Lso /tmp/containerpilot.tar.gz \
    https://github.com/joyent/containerpilot/releases/download/2.6.0/containerpilot-2.6.0.tar.gz \
    && tar zxf /tmp/containerpilot.tar.gz -C /usr/local/bin

COPY containerpilot.json /containerpilot.json
```

Whereupon I get the same panic:

```
2017/01/27 14:54:28 Unable to parse command arguments: received zero-length argument
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45f1c7]

goroutine 1 [running]:
panic(0xb51260, 0xc82000a070)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/joyent/containerpilot/core.(*App).Run(0xc8200b42a0)
        /cp/src/github.com/joyent/containerpilot/core/app.go:139 +0x227
main.main()
        /cp/src/github.com/joyent/containerpilot/main.go:25 +0xf1
```

**Comment by tgross** [comment]
We're hitting the null pointer exception [here](https://github.com/joyent/containerpilot/blob/348b2544c8eb7a4edb234665a0cace0da6b0262e/core/app.go#L139) where we assign the dummy name "APP" to `cmd` (this name is for the logger). But we shouldn't be doing this if `cmd` is `nil`, so it just needs to be moved to after the null check. PR with test incoming.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/276

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.6.1
