### ISSUE TITLE
Container pilot should log failed health check

### ISSUE THREAD

**Issue by rickardrosen** [joyent/containerpilot#267]
We spent some time trying to figure out why containerpilot did not register our container with service discovery (consul).

Turned out that, for whatever reason, we had the wrong path for our health check...
Our bad, but we could not see anything logged from containerpilot regarding the initial failed health check, even after enabling debug logging.

Even though this was a configuration error, it would be great to be able to pick this kind of issue up immediately through CP logging, or did we overlook something here?

**Comment by tgross** [comment]
Yeah, you definitely should be seeing logs if the command has the wrong path. [`RunWithTimeout`](https://github.com/joyent/containerpilot/blob/9397588538e42b6fca0876d9b57758681917a548/commands/commands.go#L133-L153) is what runs the commands in the health check. Assuming your logging in debug you should be seeing something like this in that situation:

```
2017/01/11 09:00:00 mycommand.RunWithTimeout start
2017/01/11 09:00:00 mycommand.Cmd.Start
2017/01/11 09:00:00 Unable to start mycommand: command not found: /usr/bin/nonexistingcommand
```

So either there's a bug or something not quite right in the config. Can you provide the version of ContainerPilot you're using and some details about your logging configuration?

**Comment by tgross** [comment]
Without more information I believe this is another case of #295, which I'll be opening a backported fix for shortly.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.7.1. I'm going to mark this as fixed and close this issue, but feel free to reopen if it looks like we missed something.
