### ISSUE TITLE
required environment variables

### ISSUE THREAD

**Issue by flyinprogrammer** [joyent/containerpilot#268]
What if in ContianerPilot config we could define a set of required environment variables, whereby if this list of 0 or more environment variables were not set, ContainerPilot would scream at you and then exit 1?

**Comment by misterbisson** [comment]
@flyinprogrammer I like the idea. 

It's certainly something you can do now using a `preStart` script. I'd love to get some feedback about how it would be used in practice by testing it that way first. 

As I thought about implementation, for example, I was curious about what error message should be returned and whether or not it's enough to simply check for the existence of the env var, or if more validation is needed.
