### ISSUE TITLE
consul http health check for services

### ISSUE THREAD

**Issue by s4z** [joyent/containerpilot#279]
Hi, are there any plans for adding support for a Consul HTTP check (or the other builtin consul checks eg. script) in the service health check?

Having support for the builtin consul health checks would save forking a process in the container every n seconds and also can make it easier to use thin containers (ie. no curl required). 

I tried using pre start / pre stop scripts to register/deregister the http checks in consul and it works fine however still get the ttl checks - it's close but not quite the same. Also thought about using co-process w/ pre start / pre stop however need the container to exit if the app exits (ie. need a service clause in the containerpilot config).

**Comment by tgross** [comment]
Doing this would mean that ContainerPilot would not be aware of the state of the applications it is managing, and that would conflict with our upcoming proposal to have ContainerPilot expose a status API. ref https://github.com/joyent/rfd/pull/13

I do wonder whether this is an additional argument for the notion of having ContainerPilot act as a Consul agent on its own (ref [this comment](https://github.com/joyent/rfd/pull/13/files#diff-e46a3afa881ad8e31ab3e880ab583b94R9))

**Comment by s4z** [comment]
When using a builtin consul health check the system could query consul when it needs the state. 


With consul agents listening on 0.0.0.0 it's possible to have containers talk to the hosts consul agent. Using the rkt default network consul is available on 172.16.28.1:8500 - this works fine when using additional networks (eg. a macvlan + dhcp).


The approach I took was to point containerpilot at the hosts instance @172.16.28.1:8500. Keeps it lightweight (even more so when running many containers per host) and keeps the connection count to the consul cluster low.


Thinking about it a bit more, having the option of health checks originating outside the container could be beneficial in cases the internal view doesn't match up with the external view (eg. network issues).

**Comment by tgross** [comment]
Yeah, if you have a host with multiple containers running on it then you wouldn't want to use Consul Agent as a coprocess. We designed that to support the case of Triton and other container-as-a-service environments where the container doesn't have access to the concept of an underlying host.

**Comment by tgross** [comment]
Although this proposal is interesting I don't think it fits with our roadmap for where we want to go with ContainerPilot. Particularly because in v3 we're going to have more states than simply healthy and unhealthy (ex. "in maintenance mode").
