### ISSUE TITLE
coprocess logs missing from container output

### ISSUE THREAD

**Issue by sourcec0de** [joyent/containerpilot#294]
Hey guys, awesome work on container pilot. This is way easier than stuffing supervisor into a container.

I've got an issue where the `coprocesses` output is not being captured.

Here's my container pilot installation script.
```
ENV CONTAINERPILOT_VERSION 2.7.0
ENV CONTAINERPILOT file:///etc/containerpilot.json
RUN export CP_SHA1=687f7d83e031be7f497ffa94b234251270aee75b \
    && curl -Lso /tmp/containerpilot.tar.gz \
         "https://github.com/joyent/containerpilot/releases/download/${CONTAINERPILOT_VERSION}/containerpilot-${CONTAINERPILOT_VERSION}.tar.gz" \
    && echo "${CP_SHA1}  /tmp/containerpilot.tar.gz" | sha1sum -c \
    && tar zxf /tmp/containerpilot.tar.gz -C /bin \
    && rm /tmp/containerpilot.tar.gz
```

Here's my `containerpilot.json`
```
{
  "consul": "consul:8500",
  "preStart": "/etc/lifecycle/preStart",
  "coprocesses": [
    {
      "name": "sync-nginx",
      "command": ["python3", "sync-nginx.py"],
      "restarts": "unlimited"
    }
  ]
}
```

I can see the process is running but the output is missing from the logs.
The process isn't crashing and it's working as expected. Any ideas?

Thanks again.

**Comment by tgross** [comment]
Are you getting _any_ log output from the container? For example, are you seeing the output of your `preStart` and/or the main process?

In any event, can you run with debug logging and drop the output here? Add the following section to your config:

```json
  "logging": {
    "level": "DEBUG",
    "format": "default",
    "output": "stdout"
  }
```

**Comment by sourcec0de** [comment]
@tgross it looks like the output was just really delayed.

I just opened my laptop again and the output was there. Odd.

**Comment by tgross** [comment]
That's strange. Can you tell me a bit about where you're deploying this? Is this all in Docker on your laptop or something like Triton?

**Comment by sourcec0de** [comment]
@tgross 

Locally: Docker for mac via `docker-compose`
Production: I'm on Google Container Engine (GKE) kubernetes.

**Comment by tgross** [comment]
And you saw this behavior in both environments?

**Comment by tgross** [comment]
Possibly related: https://github.com/joyent/containerpilot/issues/295

**Comment by sourcec0de** [comment]
@tgross I did see this issue on both environments.

I'll continue my comments on #295

**Comment by tgross** [comment]
Added a comment here for this: https://github.com/joyent/containerpilot/issues/295#issuecomment-288156907

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/2.7.1. I'm going to mark this as fixed and close this issue, but feel free to reopen if it looks like we missed something.

**Comment by sourcec0de** [comment]
@tgross it's resolved.

Thanks for the awesome work.
