### ISSUE TITLE
Co-processes feature request 

### ISSUE THREAD

**Issue by yellowmegaman** [joyent/containerpilot#296]
I'd like to put this idea up for discussion. 

I would be great if a co-process could be tweaked so it starts right away, not waiting for preStart to complete.

Use case:
1) I don't want to run supervisord/runit/s6
2) i want to run consul agent as a co-process
3) preStart has leader election based on consul sessions/keys
4) i want to register sessions against local consul agent so when it leaves, sessions get expired

If i create new session against some consul agent that won't be terminated when container is terminated, session will remain. I don't like all this `renew`  stuff, consul agent leave event is just more efficient.

Is it hard/ok by design to implement?
Something like:

```
"coprocesses": [
    {
      "name": "consul_agent",
      "command": ["consul", "agent", "etcetera", "etcetera"],
      "restarts": "unlimited",
      "start_after": "init"
    }
  ]
```

Thanks a lot in advance!

**Comment by tgross** [comment]
Co-processes are being removed in ContainerPilot v3 in lieu of supporting multiple first-class processes. That is, all the processes will be co-processes. This will allow you to specify dependency chains explicitly (or just start immediately!) just as you're asking for here.

See https://github.com/joyent/rfd/blob/master/rfd/0086/multiprocess.md for the design doc for this and keep an eye on https://github.com/joyent/containerpilot/pull/290 and https://github.com/joyent/containerpilot/issues/283 for progress.

**Comment by yellowmegaman** [comment]
Awesome! So i'll have to rewrite all my configs :smiley:

Hope this feature will land in releases anytime soon)
