### ISSUE TITLE
Failing unit tests on latest CP3 preview

### ISSUE THREAD

**Issue by cheapRoc** [joyent/containerpilot#298]
I'm unable to receive consistent unit test results on the latest master, `1fd7ea0`.

I've re-cloned and pulled down a fresh copy. Running `make build` results in a proper build container so I'm able to build and run tests properly. I receive either a hang waiting for Consul for `TestWithConsul`, a failed `TestServiceRunPeriodic` due to inconsistent number of task fires, or passing tests all together. So far, anything else runs as I'd expect it would.

Still debugging but here's the most frequently failed test I receive on a fresh clone...

```
=== RUN   TestServiceRunPeriodic
time="2017-03-24T18:45:35Z" level=warning msg="myservice timeout after 10ms: '[doStuff runPeriodicTest]'"
time="2017-03-24T18:45:35Z" level=error msg="myservice exited with error: myservice: signal: killed"
time="2017-03-24T18:45:35Z" level=warning msg="myservice timeout after 10ms: '[doStuff runPeriodicTest]'"
time="2017-03-24T18:45:35Z" level=error msg="myservice exited with error: myservice: signal: killed"
time="2017-03-24T18:45:35Z" level=warning msg="myservice timeout after 10ms: '[doStuff runPeriodicTest]'"
time="2017-03-24T18:45:35Z" level=error msg="myservice exited with error: myservice: signal: killed"
--- FAIL: TestServiceRunPeriodic (0.10s)
        services_test.go:151: expected 9 or 10 task fires but got 5
                [{Startup global} {ExitSuccess myservice} {ExitSuccess myservice} {ExitSuccess myservice} {ExitFailed myservice} {Error myservice: signal: killed} {ExitFailed myservice} {Error myservice:signal: killed} {ExitSuccess myservice} {ExitSuccess myservice}]
FAIL
exit status 1
FAIL    github.com/joyent/containerpilot/services       0.388s
```

**Comment by tgross** [comment]
I've done a clean build here and can't seem to reproduce this yet, with either `make test` (running in a Docker build container in Docker For Mac) or `make local test` (running on MacOS on metal).

For `TestServiceRunPeriodic`, it looks like you're getting timeouts after 10ms configured for that test, which suggests that 10ms isn't long enough for your test rig to launch the shell script under test and clean up after itself. Maybe we just need to bump that timeout up and then bump the length of that test too?

For `TestWithConsul` is the only set of tests where launch an actual Consul server (ideally we'd eliminate that entirely but the number of tests where we require it has been reduced a bunch). Is the Consul server being launched when you run that? Are you getting anything interesting in its logs?

**Comment by cheapRoc** [comment]
Unsure what the problem was but cleaning out Docker fixed the issue for the moment. I still get a few hangs on Consul coming up but they're timing out and passing again. Also, `make local test` definitely passes consistently.
