### ISSUE TITLE
Move JSON fragments into tests/fixture package

### ISSUE THREAD

**Issue by cheapRoc** [joyent/containerpilot#299]
I think it would be beneficial to move many of the JSON fragments into their own fixtures directory/package, possibly under `tests/`. It'll be easier to ensure code formatting rules of certain editors and remove the possibility of reformats causing failures for some JSON parser tests. Some of these tests (`core/app_test.go`) look for specific ranges like lines/cols and editors that reformat will break the tests. `git status` is the only way to see the difference and can lead to some headaches.

This is also super simple and could help contributor dev experience, especially other people that still use Emacs (*cough*me*cough*).

I can submit a PR for this but I wanted to double check first.

**Comment by cheapRoc** [comment]
Also, I don't believe `gofmt` honors reformatting string literals, which is the exact problem I have.

**Comment by cheapRoc** [comment]
Actually, if CP is moving to YAML I might not even need to do this.

**Comment by tgross** [comment]
It does seem like a good idea even with a config language change -- the tiny single-line snippets in some of the tests don't really need it but certainly for some of the big ones this makes sense.

**Comment by tgross** [comment]
Done in #311
