### ISSUE TITLE
control socket tests fail on MacOS

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#306]
A fairly minor item for the v3.0.0 TODO pile: running the `control` package's unit tests fails on MacOS because the control socket directory `/var/run` won't typically be owned by the user. We should have the unit tests open the socket within `/tmp` or somewhere similar.

cc @cheapRoc if you feel like hitting this as you do some of the other control plane work

**Comment by cheapRoc** [comment]
Ahhh, yes, you did mention using `/tmp` at some point before my PR. Not a problem adding this in.
