### ISSUE TITLE
add subcommands for control plane clients

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#340]
The control plane described in [RFD86](https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md) uses a unix domain socket rather than a TCP endpoint. One usability problem with this is that the `curl` that ships with most distros (anything pre 7.40) does not support sockets, and `netcat` is a portability pain because seemingly every distribution has a different version of `netcat` with different command line flags. This isn't a problem for applications like autopilotpattern/mysql or other applications that have a lot of custom code, but it's not a great experience for blueprints that are mostly standalone 3rd-party applications like autopilotpattern/nginx.

We can make this partially less annoying by providing subcommands for the end user, which in turn send HTTP requests to the socket. Here's a proposed syntax. Note these are using the stdlib flags library for golang command line args (i.e. weird plan9-like syntax), just as our `containerpilot -version`, `containerpilot -config`, and `containerpilot -render` options do now.

- `containerpilot -reload`
- `containerpilot -maintenance enable`
- `containerpilot -maintenance disable`
- `containerpilot -putenv 'MY_ENV=my_val'` -putenv 'MY_OTHER_ENV=my_other_val'
- `containerpilot -putmetric 'MY_METRIC=my_val'`

**Comment by cheapRoc** [comment]
I'd actually like to take this if I have time next week/soon.

**Comment by tgross** [comment]
Sure thing! I've got a few implementations using `netcat` (messily) in ce0d0eb and [`reload-containerpilot.sh`](https://github.com/joyent/containerpilot/blob/master/integration_tests/fixtures/app/reload-containerpilot.sh#L5-L6) if you want to draw on that for inspiration outside the unit tests we've got.

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3
