### ISSUE TITLE
provide a way to flush the event bus

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#344]
Right now we don't have a way to flush the event bus. This results in a lot of ceremony in testing where we have to set up a separate consumer of the event bus and ensure we've pulled _n_ events (whatever we expect). It also means we need to have a buffered channel for closing the event bus rather than having this be a blocking operation that we could use to force a bit more sanity into config reloads.

**Comment by tgross** [comment]
https://github.com/joyent/containerpilot/issues/332 is almost certainly related to this item.

**Comment by cheapRoc** [comment]
I'm sure your PR/diff will demonstrate the idea you had in mind but I'm curious where the flush will change existing API surface area. Also, will this replace or augment all of the event bus/debug subscriber setup work in each test?

**Comment by tgross** [comment]
> I'm sure your PR/diff will demonstrate the idea you had in mind but I'm curious where the flush will change existing API surface area.

I'm still getting it together but essentially `events.Subscriber` will wrap a `sync.WaitGroup` and expose `Add()`, `Done()`, and `Wait()`. This way `Job`, `Watch`, etc. can increment the internal wait group for each event they process and decrement it when done. Tests can call `Wait` after publishing all the test events to force the processing of all of them. (I suspect we'll never call `Wait` in the production code though, only `Close`, but I'm still working that detail out.)

> Also, will this replace or augment all of the event bus/debug subscriber setup work in each test?

Yeah, this would get rid of `DebugSubscriber` entirely which I find to be both clunky and error-prone to use. I'll probably add is a ring buffer of events to the event bus, so that we can say "hey EventBus, what were the last _n_ events you published?"

**Comment by tgross** [comment]
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3
