### ISSUE TITLE
drop exec from sensors

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#373]
After seeing @misterbisson working on improving the sensor config for our v2 Nginx blueprint (ref https://github.com/autopilotpattern/nginx/pull/49), and then working on the docs PR #371, I'm thinking we should drop the `exec` field from the `sensors` configuration.

Instead the `sensors` would only configure the Prometheus metrics that we _expect_ to receive. And then it would be up to a `job` running periodically to record those metrics. This would have a couple of advantages:

- A single job can record multiple metrics in a single execution by passing multiple `-putmetric` flags to ContainerPilot (or multiple HTTP POSTs to the control socket). This would reduce overhead in cases where there are multiple metrics on the same application, and could help eliminate mistakes like https://github.com/autopilotpattern/nginx/issues/48#issuecomment-301589006.
- We wouldn't have to make an awkward documentation case for why `watches` don't have their own exec but `sensors` do.
- It would emphasize the core abstraction of jobs + events.
- Sensors would no longer be a special case of an exec, reducing our surface area for ContainerPilot bugs.

Thoughts @misterbisson or @cheapRoc? Internally the change would be totally trivial. But this would be a breaking config change, so we'd want to get it into v3.0.0 rather than waiting until a later v3.x.

**Comment by misterbisson** [comment]
This makes sense.

We also should consider that Prom exporters for some apps are likely a better choice than our implementation. Consider:

https://github.com/knyar/nginx-lua-prometheus/blob/master/README.md

https://github.com/prometheus/mysqld_exporter

I don't think there's anything more we need to do to make those easier to run with ContainerPilot, though we might consider changing the default port to leave room. 

There's also an argument that ContainerPilot should expose more of its internal metrics, as the Prometheus app does.

**Comment by tgross** [comment]
> We also should consider that Prom exporters for some apps are likely a better choice than our implementation.

Sure, although that's pretty much the case with every ContainerPilot feature. Most of what we're doing can be done more cleanly by a dedicated implementation, and ContainerPilot serves more as a "how do I workaround my lack of that dedicated implementation?" (ex. legacy lift-and-shift applications).

> There's also an argument that ContainerPilot should expose more of its internal metrics, as the Prometheus app does.

Agreed. I have some TODOs sprinkled around the code for figuring out just what those might be other than the golang runtime info (which we already expose).

**Comment by cheapRoc** [comment]
I concur, it feels right to me to centralize the use case around `jobs`. I believe this places even greater utility on the `jobs` configuration/API and removes yet another vector of `exec` confusion. This feels more like CPv3.

> Instead the sensors would only configure the Prometheus metrics that we expect to receive.

You might want to change `sensors` to just `metrics` in order to solidify the fact that these aren't "sensing" anything but waiting for input. I feel like the `sensors` language pairs better with execution of a script, but I could be wrong.

**Comment by tgross** [comment]
> You might want to change `sensors` to just `metrics` in order to solidify the fact that these aren't "sensing" anything but waiting for input. I feel like the `sensors` language pairs better with execution of a script, but I could be wrong.

Agreed.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-RC1
