### ISSUE TITLE
what internal metrics do we want?

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#374]
This is only somewhat related to https://github.com/joyent/containerpilot/issues/154 (which will be implemented via the [`/status` endpoint](https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md#getstatus-get-status)), and more along the lines of @misterbisson's suggestion https://github.com/joyent/containerpilot/issues/373#issuecomment-302699022.

Right now we only expose the Prometheus metrics for the golang runtime. Are there other metrics that might be useful for us to expose about ContainerPilot via the telemetry interface? Right now the only thing I can think of is the rate of events being processed, although admittedly I'm not even sure what you'd do with that info.

**Comment by cheapRoc** [comment]
Going to shoot these out there for open discussion. Interested to hear everyone's opinions regardless, even if they overlap.
- successful jobs (`$? == 0`)
- failed jobs (`$? > 0`)
- expired jobs
- successful reloads
- expired reloads
- maintenance mode state changes
- HTTP status 200 endpoint responses
- HTTP status non-200 endpoint responses
- control socket requests regardless of status code
- number of registered Consul backends
- number of deregistered Consul backends

Those are the only internal ContainerPilot gauges I can think of that users can't harvest themselves.

**Comment by tgross** [comment]
What are "expired" jobs and reloads?

**Comment by cheapRoc** [comment]
Jobs that are timing out given a specific timeout period.

Reloads would be configuration reloads but that's probably far less applicable than anything else.

**Comment by jhmartin** [comment]
Knowing how often a task has returned nonzero, or a coprocess has exit (at all) and been restarted would be very useful.

**Comment by tgross** [comment]
I've opened https://github.com/joyent/containerpilot/pull/432 for review and discussion.

**Comment by tgross** [comment]
#432 has been merged and this is now awaiting release.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.2.0
