### ISSUE TITLE
Connection still possible when a backend event is received

### ISSUE THREAD

**Issue by lucj** [joyent/containerpilot#380]
I have several services depending on a rabbitmq backend.
When I stop rabbitmq (from Compose) an event is sent and each service retries the connection.
It seems that from time to time the connection is still possible for a couple of seconds after the event is received. Is there a mecanism that could prevent that, or should I use a sleep in the script managing the event ?

**Comment by tgross** [comment]
ContainerPilot polls for changes in the list of addresses in Consul, and the `onChange` handler is executed at that point. This means that if your backend is stopped it will take `n` seconds for the state of the whole system to converge (where `n` is your poll interval + the time it takes for the `onChange` to execute). The behavior of your client and the `onChange` behavior is totally up to you.

It looks to me like you want to have a graceful shutdown of the RabbitMQ service so that all clients have disconnected. You can tell ContainerPilot you're intending to do this by sending it `SIGUSR1`. It'll then deregister itself from Consul and your clients will get their `onChange` behavior. The RabbitMQ server will still be up, so clients that haven't run their `onChange` yet will still have a server to talk to. Once all the clients have disconnected from the RabbitMQ instance, then you can shut it down.

(Note that I'm assuming we're talking about ContainerPilot v2 here. In CPv3 you would send an HTTP POST to `/v3/maintenance/enable` instead.)

**Comment by lucj** [comment]
What I have in mind is more related to a case where RabbitMQ is stopped by issuing a ```docker-compose stop mq``` (mq being the name of the RabbitMQ service in the compose stack).
It seems to me that sometimes the service that depends on RabbitMQ try to reconnect (because it has received an onChange event) before the RabbitMQ has finished its shutdown. In this case the service can reconnect as for it RabbitMQ is healthy (where in fact it's not anymore).
Yes, I'm using v2.

**Comment by tgross** [comment]
> It seems to me that sometimes the service that depends on RabbitMQ try to reconnect (because it has received an onChange event) before the RabbitMQ has finished its shutdown. In this case the service can reconnect as for it RabbitMQ is healthy (where in fact it's not anymore).

The `onChange` handler doesn't get fired until the IP address for that RabbitMQ instance has been removed from Consul. So your `onChange` handler needs to make sure it's only connecting to instances registered in Consul and marked healthy. This is easy to get wrong if you're querying Consul in the `onChange` handler; I just had to fix an example of this in one of our integration tests (ref https://github.com/joyent/containerpilot/pull/377/commits/8ff2c85affc53828599383216f76a4b2810f6788).

If you can share your `onChange` handler hook behavior I might be able to point out where it's grabbing the wrong data from Consul.

**Comment by lucj** [comment]
My onChange handler is quite simple in fact. It's a single _manage.sh_ script that is used for handling both _prestart_ and backends events.
In the case an event is received from a backend, a SIGHUP is sent that forces the node process to retry the connection to the backend. Am I missing something here ?


```
#!/bin/sh

# Get event received
event=$1
echo "Event received:[$event]"

### Handle prestart events
# Make sure mongo, redis and rabbitmq are registeted in Consul before starting up
if [ "$event" = "prestart" ];then
  echo "-> Prestart <-"

  # Check RabbitMQ
  while [[ "$(curl -s http://${CONSUL:-consul}:8500/v1/health/service/rabbitmq | grep passing)" = "" ]]
  do
    echo "mq is not yet healthly..."
    sleep 5
  done
  echo "mq is healthly, moving on..."

  exit 0
fi

### Handle backends events

# Handle rabbitmq event
if [ "$event" = "rabbit-event" ];then
  pkill -SIGHUP node
fi
```

**Comment by tgross** [comment]
> In the case an event is received from a backend, a SIGHUP is sent that forces the node process to retry the connection to the backend

Ok, this looks good. Unless there's more code here that you didn't share it looks like your `onChange` handler could just be `pkill -SIGHUP node` for that section of the ContainerPIlot. But this should work regardless.

How is the node process finding out which backend to connect to when it gets the SIGHUP?

**Comment by tgross** [comment]
> Is that possible that a backend is deregistered from Consul before it's actually down (that would explain the service can still connect to it for a couple of secs) ?

Yes. On receiving SIGTERM we deregister from Consul immediately and then proceed to shutdown the application. This has to be the case or it's impossible to have graceful shutdown. (But if the shutdown takes too long we get SIGKILL by Docker/Triton and that will not be graceful.) 

> When a service receives the SIGHUP, it will try to reconnect to each backends it depends on (might not be that good I admit...)

Right. The client needs to make sure it's reconnecting only to backends that are currently showing as healthy in Consul. It's the responsibility of the client to handle this behavior.

**Comment by tgross** [comment]
@lucj you might want to check out https://github.com/joyent/node-piloted, which implements the behavior for querying Consul and caching the address/port information in memory.

**Comment by lucj** [comment]
Currently, I use node-piloted in the following way. Basically, when the application start (once it has left the _prestart_ state), I connect to the backend (on one, mq, in this service). Each time I get a refresh I retry the connection

```
// Manage connection to the underlying backends
Piloted.config(ContainerPilot, (err) => {
    winston.info("ContainerPilot configuration:" + (err ? err.message : "ok"));

    // Connect to message queue
    mq.connect(function(err, channel){
        if(err){
            winston.error(util.format("-> app: mq.connect failed:[%s]", err.message));
            process.exit(1);
        }
        winston.info(util.format("-> app: mq.connect succeeded"));

        // Run wss server
        init();

        // Run http server
        www.start((msg) => {
            winston.info(msg);
        });
    });

    // Reconnect when ContainerPilot reloads its configuration
    Piloted.on('refresh', () => {
        // MQ reconnection attempt
        mq.reconnect(function(err) {
            if(err) {
                winston.error(util.format("-> app: mq.reconnect failed:[%s]", err.message));
            } else {
                winston.info(util.format("-> app: mq.reconnect succeeded"));
            }
        });
    });
});
```

If the reconnection cannot be done, the /health route (that checks if the service can reach the backend) will return a 503.

```
/*
 * Check application health
 */
app.get('/health', (req, res) => {
    mq.checkConnection((err) => {
        if(err){
            winston.error(util.format("Health:%s", err.message));
            return res.sendStatus(503);
        }
        return res.sendStatus(200);
    });
});
```

**Comment by tgross** [comment]
As far as I understand there's no problem with triggering the reconnect, right? The problem is that when we reconnect it reconnects to the stopped instance. So the code we need to see is the `reconnect` code.

**Comment by lucj** [comment]
Here is the code to reconnect to the MQ backend. _connection_ function is called by _reconnect_.

 _reconnect_ is triggered when a _onChange_ event is received, the mq channel is invalidated and then a connection to mq is retried. As sometimes the connection goes through, it seems mq is still available (even if it not in registered in Consul) as you explained above. 

```

function connection(callback){
    // Check if channel is already instantiated
    if(channel) {
        return callback(null, channel);
    }
    winston.debug("-> mq.connection: channel object is not instantiated");

    // Get new channel
    amqp.connect(config.mq.url, function(err, conn) {
        if(err){
            channel = null;
            return callback(err);
        }

        if(!conn){
            channel = null;
            return callback(new Error("Cannot create connection"));
        }

        conn.createChannel(function(err, ch) {
            if(err){
                channel = null;
                winston.error(util.format("Cannot create channel:[%s]", err.message));
                return callback(err);
            }

            // Save channel so it does not have to be created each time
            channel = ch;

            // Bind queues
            bind(channel, function(err){
                if(err){
                    channel = null;
                    return callback(err);
                } else {
                    return callback(null, channel);
                }
            });
        });
    });
}

module.exports = { 
   /*
     * Reconnect to the queue
     */
    reconnect: (cb) => {
        winston.debug("-> mq.reconnect");

        // Invalidate channel object
        channel = null;

        // Connection attempt to MQ
        connection( (err, ch) => {
            if(err){
                channel = null;
                return cb(err);
            } else {
                channel = ch;
                return cb(null, channel);
            }
        });
    }
},
...
```

**Comment by tgross** [comment]
@lucj it looks like you're not updating the `config.mq.url` here. When `node-piloted` refreshes the list of services hosts in `config` from Consul, you need to update `mq.url` to pick up that change. I think you can do that with that library via [`serviceHosts`](https://github.com/joyent/node-piloted#servicehostsname).

**Comment by geek** [comment]
In the latest version of piloted you can use the environment variable (`CONTAINERPILOT`) to point to the ContainerPilot configuration file. Below is updated code that should help with the reconnection logic. You may not want to reconnect when a new amqp instance is registered in consul, instead, you may want to try reconnecting when the existing connection has an error...

```javascript
function getHosts () {
  const services = Piloted.serviceHosts('amqp');
  return services.map(service => service.address);
}

const connection = amqp.createConnection({ host: getHosts() });

connection.on('error', () => {
  connection.options.host = getHosts();
});
```

amqp will reconnect by default, the above code simply refreshes the list of hosts from consul anytime there is an error with the connection to one host. amqp also supports passing in multiple hosts and it will randomly try the array, this is why I am setting the hosts to an array above.

**Comment by lucj** [comment]
Thanks for the code, I will check this.
Currently I'm using amqplib which behave differently than node-amqp, but that might be the opportunity to test another lib though.

**Comment by lucj** [comment]
There is still something that is not very clear to me. When implementing a health check fonction, which approach do you recommend:
- checking the application is running and all the backends can be reached within the application
- checking the application is running and all the backends are flagged healthy within Consul

**Comment by tgross** [comment]
> When implementing a health check fonction, which approach do you recommend

As with a lot of monitoring & automation, the exact answer to this is going to be specific to the application and the business goals it needs to fulfill.

But for my own HTTP applications I usually check not that the application is _running_ but that it is _serving successful requests_.

Ideally if the backends aren't available then the application behavior should degrade gracefully, in which case the application should still pass health checks by returning 200. If the application behavior can't degrade gracefully, then I have the application return 503 on HTTP requests so that it's marked unhealthy.

**Comment by lucj** [comment]
@tgross ok, I got it. I was not sure about what you meant regarding the health check sending a 200 even if the backends are not available. I have several services which cannot provide the business features if the backends they depends on are not available, but some other services can run in degraded mode as you said. I need to make sure this is correctly handled then. Thanks for your help.

**Comment by tgross** [comment]
Glad we could be of help @lucj
