### ISSUE TITLE
make check registration atomic with service registration

### ISSUE THREAD

**Issue by cirocosta** [joyent/containerpilot#391]
*Maintainers note: this originally was a usage question / bug report but we're making it into a v3 enhancement. See https://github.com/joyent/containerpilot/issues/391#issuecomment-308717507 for where this was decided. The original issue report is below:*

---

Hey,

this morning I noticed that on my consul cluster I had a service without a check associated with and wondered whether that could have happened due to how `containerpilot` registers services and checks. From the code it looks like the situation indeed can happen as service registration is separated from check registration (https://github.com/joyent/containerpilot/blob/f5938e8b429c0ff9b8f059b0e02fa5c80849e94e/discovery/service.go#L52-L56):

```go
		if err = service.registerService(); err != nil {
			log.Warnf("service registration failed: %s", err)
			return
		}

                // if something goes wrong with the process here we
                // can have a service w/out check 

		if err = service.registerCheck(); err != nil {
			log.Warnf("check registration failed: %s", err)
			return
		}
```

As I see we could instead register the check right at the service definition (https://www.consul.io/docs/agent/services.html#service-definition) such that a service registration would guarantee to have a check registered as well.

```json
{
  "service": {
    "name": "redis",
    "tags": ["primary"],
    "address": "",
    "port": 8000,
    "enableTagOverride": false,
    "checks": [
      {
        "script": "/usr/local/bin/check_redis.py",
        "interval": "10s"
      }
    ]
  }
}
``` 

Does that make sense? Are there any reasons for separating the registrations?

Thx!

(and great project by the way 🙌  😄 )

**Comment by tgross** [comment]
Yes, services can be registered without a check. Note that if we fail to register the check after registering the service it won't be marked healthy and the subsequent pass through the heartbeat handler will register the check again.

**Comment by cirocosta** [comment]
Hmmm that makes sense. 

I was thinking about the case where the container dies in the middle - thus it doesn't have the heartbeat handler registering it again (as the container is recreated with a different container ID, thus with different serviceID and different checkID as well). Or am I missing something? 

Thx @tgross !

**Comment by tgross** [comment]
> I was thinking about the case where the container dies in the middle - thus it doesn't have the heartbeat handler registering it again (as the container is recreated with a different container ID, thus with different serviceID and different checkID as well).

Sure but in which case that container won't ever get marked healthy, right?

**Comment by cirocosta** [comment]
Hmmm if I register a service w/out specifying checks it is marked healthy if serf is fine:

```sh
curl http://localhost:8500/v1/agent/service/register \
  -XPUT \
  -SL \
  -d '{
   "ID": "service-id",
   "Name": "service",
   "Address": "127.0.0.1",
   "Port": 123
  }'

...

curl -s localhost:8500/v1/health/service/service | jq
[
  {
    "Node": {
      "ID": "c0a1901a-55b9-c712-50d4-434403879076",
      "Node": "46a4eb5decb9",
      "Address": "10.0.240.3",
...
    },
    "Service": {
      "ID": "service-id",
      "Service": "service",
      "Tags": [],
      "Address": "127.0.0.1",
      "Port": 123,
...
    },
    "Checks": [
      {
        "Node": "46a4eb5decb9",
        "CheckID": "serfHealth",
        "Name": "Serf Health Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Agent alive and reachable",
...
      }
    ]
  }
]
```

or am I confusing things?

**Comment by cirocosta** [comment]
Oooh, yeah, I'm confusing, if I check `curl localhost:8500/v1/health/state/passing | jq` naturally the service is not there 👍

**Comment by cirocosta** [comment]
The question comes from the fact that using a dummy template on `consul-template` like

```
{{ range service "service"}}
	{{ . | toJSON }}
	{{ .Name }} {{ .Address }}:{{ .Port }}
{{ end }} 
```

would lead to 

```
	{"Node":"46a4eb5decb9","NodeAddress":"10.0.240.3","Address":"127.0.0.1","ID":"service-id","Name":"service","Tags":[],"Checks":[{"Node":"46a4eb5decb9","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":""}],"Status":"passing","Port":123}
	service 127.0.0.1:123
```

having registered it without checks, making `consul-template` render the service as `status ==passing` (even though that's because of serf). 

Do you have any recommendations for this case?

Thx again!

**Comment by tgross** [comment]
Per the `consul-template` docs:

> To filter services by a specific set of healths, specify a comma-separated list of health statuses:
> `{{ service "web|passing,warning" }}`

**Comment by cirocosta** [comment]
Yeah, that's the point why I was asking 😁  it remains `Status: passing` thus filtering by `passing` doesn't help. But I think that's something for `consul-template` and not this repo.

Thx!

**Comment by tgross** [comment]
Ok. If you can give us a minimal repro (ideally with the CPv3 release candidate), then I'd be happy to look into it further. It may be that we want the registration to be atomic now that we've dumped etcd, but in v2 we can't do both at the same time as far as I know.

**Comment by tgross** [comment]
Ok this appears to have a suitable workaround for v2 and isn't strictly a bug so long as we have to support etcd in v2. But I'm going to mark this as a v3 enhancement to make the check registration atomic with the service registration, which we can do in v3 because Consul can do it in a single request.

This will mean updating [`discovery/ServiceDefinition.SendHeartbeat`](https://github.com/joyent/containerpilot/blob/92bd0c5a5063a9cc3051c510b8c2810d2da6582b/discovery/service.go#L39-L67) so that we send the [`/agent/service/register` call](https://www.consul.io/api/agent/service.html#register-service) that includes both check definition and an initial status of "passing".

**Comment by cirocosta** [comment]
Hey @tgross , sorry for not providing the reproducible example. Thx for following up!

**Comment by tgross** [comment]
Going to snag this as part of a batch of post-v3 Consul-related improvements.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/403

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.1.0
