### ISSUE TITLE
File function

### ISSUE THREAD

**Issue by ahelal** [joyent/containerpilot#392]
Hi @tgross I was playing the around with telemetry interface. And although it possible to use the new environment loop, it would be simpler and cooler to be able to load this from a file system.
i.e. 
```json
"telemetry": { {{ file "/etc/app1_telemetry.json" }}
}
```
Let me know if that make sense and works for you 👍 

Cheers,
Adham

**Comment by ahelal** [comment]
Just as a follow up i think it should be static loading no further interpolation will happen smiler to [consul-template](https://github.com/hashicorp/consul-template#file)

**Comment by tgross** [comment]
Our current thinking on this was to use a `.d`-style configuration directory that sums together all the config files. See https://github.com/joyent/containerpilot/issues/236
