### ISSUE TITLE
3.0 exit on job fail

### ISSUE THREAD

**Issue by jhmartin** [joyent/containerpilot#394]
How does one tell CP 3.0 to shut down if one of the jobs fails? In the nginx example, I want the entire container to exit if nginx fails, while I am tolerant of other jobs failing and restarting.

**Comment by tgross** [comment]
You'll want to add a job to respond to the `stopped` event for the job you want to exit on. And that job will want to send a SIGTERM to ContainerPilot so it does a graceful shutdown. So for example:

```json5
jobs: [
  {
    name: "nginx"
  },
  {
    name: "onExit",
    exec: "pkill -signal SIGTERM containerpilot",
    when: {
      source: "nginx",
      once: "stopped"
    }
  }
]
```

**Comment by jhmartin** [comment]
Oh, I hadn't considered that. That looks like just the ticket.

**Comment by cheapRoc** [comment]
Came here from #526 and wanted to leave a note about UX. In reference to the `onExit` job above, I believe it's handy to leave the shutdown mechanism in the hands of users. We enabled this style of lifecycle handling with #513.
