### ISSUE TITLE
Non-service job names validated as service names

### ISSUE THREAD

**Issue by geek** [joyent/containerpilot#397]
`unable to parse jobs: service names must be alphanumeric with dashes to comply with service discovery`

On 3.0.0-RC1

Example of invalid job name:
```
{
      name: 'onchange_influxdb',
      exec: 'pkill -SIGHUP node',
      when: {
        source: 'watch.influxdb',
        each: 'changed'
      }
},
```

This job won't be registered with Consul but is still validated as such. Can we only enforce naming restrictions on services?

**Comment by tgross** [comment]
That's supposed to already be the case (ref [jobs/config.go#L107-L115](https://github.com/joyent/containerpilot/blob/3965d4f4f117ea9f3ecc9bb0bb217251e66e9165/jobs/config.go#L107-L115)). This looks like this is a bug.

Off the top of my head I'm not sure how that got introduced but probably during some refactoring of the validation code. The validating of the service name should be happening inside the `validateDiscovery` method. Easy to fix and I'll get that in for v3-final.

**Comment by tgross** [comment]
Ok, looks like the test [here](https://github.com/joyent/containerpilot/blob/3965d4f4f117ea9f3ecc9bb0bb217251e66e9165/jobs/config_test.go#L243) doesn't correctly verify the logic there. If I add a 4th case to that test like so:

```go
	cfgD := `[{name: "myjob_invalid_name", exec: "myexec"}]`
	_, err = NewConfigs(tests.DecodeRawToSlice(cfgD), noop)
	if err != nil {
		t.Fatal(err)
	}
```

then I get the error you're getting:

```
go test -v -run TestJobConfigValidateName
=== RUN   TestJobConfigValidateName
--- FAIL: TestJobConfigValidateName (0.00s)
        config_test.go:254: service names must be alphanumeric with dashes to comply with service discovery
FAIL
exit status 1
FAIL    github.com/joyent/containerpilot/jobs   0.011s
```

**Comment by tgross** [comment]
So right now it looks like the intent is that we're supposed to allow blank names in all cases and that's complicating the logic a bit. But I'm not sure there's any good reason to allow that (it results in really goofy stuff with setting up `when` events based on that job), so I'm going to take advantage of this being the backwards-compatibility breaking v3 release and cutting that option.

**Comment by tgross** [comment]
Opened https://github.com/joyent/containerpilot/pull/398 with the fix.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.0.0
