### ISSUE TITLE
Additional telemetry server listener on localhost

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#399]
Currently the telemetry server does not listen on localhost. For example, the container we use for our integration test of the telemetry server has the default binding:

```
root@7c2f6b1aebc0:/# curl -s 192.168.16.3:9090/metrics | head -4
# HELP containerpilot_app_some_counter help text
# TYPE containerpilot_app_some_counter counter
containerpilot_app_some_counter 42
# HELP go_gc_duration_seconds A summary of the GC invocation durations.

root@7c2f6b1aebc0:/# curl -sv 127.0.0.1:9090/metrics
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 9090 failed: Connection refused
* Failed to connect to 127.0.0.1 port 9090: Connection refused
* Closing connection 0
```

This is intentional behavior and it results from binding to particular addresses that are provided by the `interfaces` field of the configuration. Containers with multiple addresses don't want to have telemetry available on all of them. The specific use case we had in mind was Docker containers on Triton Cloud, which have a private IP address on eth0 and (optionally) a public IP address on eth1. That is, we don't want the following behavior described in the stdlib [net.Listen](https://golang.org/pkg/net/#Listen) docs:
>  If host is omitted, as in ":8080", Listen listens on all available interfaces instead of just the interface with the given host address. 

But @geek has raised a possible usability issue with this, which is that it makes it annoying for a job to check its own metrics without trying to figure out what IP address the telemetry server is bound to.

I think we can correct this by adding a second binding to localhost to the [`Telemetry.Start`](https://github.com/joyent/containerpilot/blob/3965d4f4f117ea9f3ecc9bb0bb217251e66e9165/telemetry/telemetry.go#L69-L96) method, but we'd have to be careful to make sure we can reload that endpoint the same way we do with the external listener.

Are there any problems with this idea that I might be missing? Alternately, is not binding on all ports for the telemetry server overly paranoid behavior?

cc @geek @cheapRoc @misterbisson

**Comment by cheapRoc** [comment]
Binding to loopback is a reasonable thing to do. And this adds default behavior secondary to what the user expects to occur when they declare an interface. I think that's ok.

For my own curiosity, I'd like to hear more about the use case for this. If an app is reporting its metrics, why/when would it need to poll those a second time?

**Comment by tgross** [comment]
> For my own curiosity, I'd like to hear more about the use case for this. If an app is reporting its metrics, why/when would it need to poll those a second time?

In the abstract, maybe a job might want metrics about another job? But what you'd use that for (that wouldn't otherwise be better handled by asking the deployment's Prometheus server) is admittedly unclear to me too.

**Comment by raykrueger** [comment]
ContainerPilot 3.0.0 requires the interfaces element to be an array. Is it not possible to bind to that?

For example...
```
  telemetry: {
    port: 9090,
    interfaces: [ "static:127.0.0.1", "l0", "eth0:inet" ]
  }
```

**Comment by tgross** [comment]
> ContainerPilot 3.0.0 requires the interfaces element to be an array. Is it not possible to bind to that?

ContainerPilot picks the first interface that matches the array (this is for both jobs and the telemetry server). Which is different from binding to more than one interface.

So in the example you gave `interfaces: [ "static:127.0.0.1", "l0", "eth0:inet" ]`, it would bind to the static IP 127.0.0.1, and not the `l0` or `eth0` interface.

**Comment by raykrueger** [comment]
That might explain another issue I'm having where it's not binding to anything :)

I'll open a separate ticket on that.

**Comment by tgross** [comment]
Following up a bit on this use case:

> which is that it makes it annoying for a job to check its own metrics without trying to figure out what IP address the telemetry server is bound to.

We expose the `CONTAINERPILOT_<SERVICENAME>_IP` environment variable for each advertised job. So a job can use `CONTAINERPILOT_CONTAINERPILOT_IP` as the IP address for the telemetry service just fine.

**Comment by tgross** [comment]
Given that we have `CONTAINERPILOT_CONTAINERPILOT_IP` I'm just going to close this. It adds extra implementation complications for not much payoff.
