### ISSUE TITLE
Add version details to containerpilot service in consul

### ISSUE THREAD

**Issue by geek** [joyent/containerpilot#419]
When registering `containerpilot` with consul create a tag named `version` or similar with the version of the ContainerPilot being registered. 

Tagging with a version will make it easier to know what features each service supports. For example, the `/status` endpoint was added in version `3.1.0` so if we have that information registered in consul we will know that we can query `/status` on the service.

**Comment by tgross** [comment]
Opened #430 with this, and added a version field to the `/status` endpoint itself as well.

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.2.0
