### ISSUE TITLE
Custom adevertisable IP

### ISSUE THREAD

**Issue by ahelal** [joyent/containerpilot#436]
Hi we intend to run container Pilot in ECS and till this point ECS doesn't support overlay. So as a work around we can advertise the docker host IP.
So modest proposal I can do a PR that can explicitly set the advertised IP.

Is that something that your open to?

**Comment by tgross** [comment]
@ahelal we've had this proposal previously https://github.com/joyent/containerpilot/issues/350. I'm going to close this, but take a look at that proposal and if you have anything you can expand upon feel free to reopen this.
