### ISSUE TITLE
Add an option to leave job's stdout/stderr alone

### ISSUE THREAD

**Issue by inetfuture** [joyent/containerpilot#437]
As of 3.x, containerpilot warps job's stdout/stderr in its own format as msg field, this behavior is different with 2.x, which just redirect service's stdout/stderr to container's.

I would love to have that old behavior back, perhaps via an option, because our underlying log collecting tool has assumptions about how the service's log should look like, with 3.x, the new format breaks our tool.

**Comment by tgross** [comment]
This would cause job logs to be interleaved and undifferentiated. It doesn't work in any case where there is more than one job, and that includes all uses of ContainerPilot where a job responds to a `watch`.

**Comment by tgross** [comment]
If we were to do this (with the caveat that I think it's not particularly usable), what would you propose as the configuration syntax?

**Comment by inetfuture** [comment]
Sorry for the delay, how about something like this:

```json5
{
  jobs: [
    {
      name: "app",
      exec: "/bin/app",
      restarts: "unlimited",
      port: 80,
      captureStdout: false,
      captureStderr: false
    },
  ]
}
```

Where `captureStdout` and `captureStderr` by default are true, means containerpliot will capture them with its logger. 

Then users like me can choose to set them to false, means containerpilot will not capture them and let them propagate up freely.

**Comment by inetfuture** [comment]
@tgross any suggestions?

**Comment by tgross** [comment]
Sorry for the delay in response here @inetfuture. That config seems somewhat sane. Maybe @misterbisson has opinions about naming of the fields too (he's good at naming things). From an implementation perspective, the ContainerPilot worker process would be the one capturing the logs, so I'm not 100% sure that we wouldn't just be dropping the logs on the floor if we tried piping them to stdout/stderr in a Docker environment. I'll have to dig into that.

**Comment by misterbisson** [comment]
> he's good at naming things

I want that as a merit badge ;-)

The question I'm struggling with, and perhaps it's a bit naive, is if this should be a job-level config item, or if it should be a [log format option](https://www.joyent.com/containerpilot/docs/configuration/logging). I mean, the effect of `captureStdout: false` will be to pass the output straight through to stdout, but not suppress other logging that ContainerPilot is passing through to stdout on its own, right?

**Comment by inetfuture** [comment]
yes

I also thought of whether we should put it inside log config section, the reason I choose jobs section is because I want job configuration to be independent, not involving modifying other parts. So when I need to include a job dynamically, like based on ENV var, there will be only one `if` needed instead of two in the template.

And technically, whether capture stdout/stderr does not necessarily related to logging, containerpilot just happens to encapsulate them into logs.

**Comment by misterbisson** [comment]
With the clarification above that this really doesn't change where the logs go, I'm having picturing a result that does something the [log format options](https://www.joyent.com/containerpilot/docs/configuration/logging) don't or can't do. I'm likely missing something, though.

**Comment by tgross** [comment]
Having a log format (`raw` seems like a good term for that) would be doable, and for applications that already have structured logs this seems like a reasonable thing to do.

But that won't give us per-job log configuration. Adding per-job log formatting is problematic because `raw` is the only way that works. There's an inherent race between the `exec` process exiting and us closing up the logger, which we fixed in #424 to avoid dropping log entries at the end of a job.

If an end-user wants more complex log formatting than that, they should probably have their applications format the logs and/or stream them off-host anyways.

**Comment by tgross** [comment]
After taking even just a second to look into the code to support this idea, I'm realizing there's a problem with the notion of `raw` top-level logging, which is that ContainerPilot needs formatting for its own logs. Emitting unformatted logs from ContainerPilot isn't really acceptable to me. So I think that brings me back around to @inetfuture's original proposal after all.

(Sometimes you really just have to look at the code! 😆  )

**Comment by tgross** [comment]
I've opened https://github.com/joyent/containerpilot/pull/462 with an implementation.

**Comment by tgross** [comment]
This has been merged and is awaiting release (will be done later today).

**Comment by cheapRoc** [comment]
Later today has moved to tomorrow AM. Apologies for any hold up.

**Comment by inetfuture** [comment]
👍

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.4.0
