### ISSUE TITLE
some child processes not being reaped

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#439]
A user has reported a problem with ContainerPilot 3.1.2 and a RabbitMQ configuration that leaves a lot of zombies. The relevant anonymized portion of their configuration looks like the following:

```json5
{
  logging: { level: "DEBUG" },
  jobs: [
    {
      name: "rabbitmq",
      exec: "rabbitmq-server",
      health: {
        exec: "rabbitmqctl node_health_check",
        interval: 30,
        ttl: 45
        timeout: "20s"
      }
    }
}
``` 

The relevant anonymized log sections:

```
2017/07/14 19:31:40 event: {Startup global}
2017/07/14 19:31:40 control: serving at /var/run/containerpilot.socket
2017/07/14 19:31:45 rabbitmq.Run start
...
(lots and lots of startup)
...
2017/07/14 19:32:10 check.rabbitmq.Run start
2017/07/14 19:32:11 Timeout: 70.0 seconds ...
2017/07/14 19:32:11 Checking health of node rabbit@0064bb4a4ea6 ...
2017/07/14 19:32:11 Health check passed
2017/07/14 19:32:11 check.rabbitmq exited without error
2017/07/14 19:32:11 event: {ExitSuccess check.rabbitmq}
2017/07/14 19:32:11 check.rabbitmq.Run end
2017/07/14 19:32:11 check.rabbitmq.kill
2017/07/14 19:32:11 killing command 'check.rabbitmq' at pid: 357
2017/07/14 19:32:11 event: {StatusHealthy rabbitmq}

```

These logs don't tell us much other than that our health checks appear to be working and getting killed as expected.

The process table shows many zombie entries for `erl_child_setup`. I'm not an expert on RabbitMQ, but it appears these are children of `/usr/lib/erlang/erts` (the Erlang service manager), which is in turn the child of `rabbitmq-server` -- our `job.exec` and not our `health.exec`. So this doesn't appear to be a regression of #409 which was fixed in 3.1.0.

My working theory is that although the fix in 3.1.0 helps out with health checks and other short-lived job `exec`s, the long-lived `rabbitmq-server` process doesn't exit and so we never hit [the defer that triggers child reaping](https://github.com/joyent/containerpilot/blob/a78b65aa62e7cbe17bc152e301498220a2b924d8/commands/commands.go#L105). My first step will be to try to verify this, but I'm having trouble creating a minimum failing test case.

(Joyent internal ref https://devhub.joyent.com/jira/browse/PRODSUP-17)

**Comment by tgross** [comment]
I suspect that the reason I was unable to reproduce simply with a long-running process is that I elided an important item above -- that the `rabbitmq-server` is being wrapped in a bash script that does `exec` itself. In this case the child process (in this case `erts`) is being reparented which puts it in a new process group, and then _its_ children aren't being reaped because they're in a different process group at that point than the one ContainerPilot expects.

**Comment by cantoine** [comment]
Tim,

I know I'm kind of jumping around support here as I'm the one that reported the issue, so I apologize for that but I'd love to try to help reproduce the issue or do any debugging on my end that could help figure it out.

I reduced my test case to just starting rabbitmq with containerpilot and a consul agent(removing the bash script from the equation) and I'm still seeing the same behavior( https://www.dropbox.com/s/eb26tdv14cadir3/Screenshot%202017-07-14%2018.50.39.png?dl=0 ).

Thanks!
Chris

**Comment by tgross** [comment]
> I know I'm kind of jumping around support here as I'm the one that reported the issue, so I apologize for that

No worries! 😀 

> I reduced my test case to just starting rabbitmq with containerpilot and a consul agent(removing the bash script from the equation) and I'm still seeing the same behavior

Ok, that's super helpful because it eliminates a bunch of different edge cases I was worried about, and that suggests this is more straightforward than I suspected and that I'm just missing something obvious in building a test case.

**Comment by tgross** [comment]
I've opened a PR for https://github.com/joyent/containerpilot/pull/440 to track progress.

**Comment by tgross** [comment]
Still haven't been able to replicate w/o using Rabbit, but I have a minimal repro with it.

Here's the ContainerPilot config file:

```json5
{
  consul: "consul:8500",
  logging: { level: "DEBUG" },
  jobs: [
    {
      name: "rabbitmq",
      exec: "rabbitmq-server",
    }
  ]
}
```

Here's me running with that config file and the out-of-the-box RabbitMQ image, mounting our config file and the current ContainerPilot build from my local machine:

```
$ make consul # run a Consul instance
$ docker run -it --rm --name rabbit \
    --link containerpilot_consul:consul \
    -v $(pwd)/build/containerpilot:/containerpilot \
    -v $(pwd)/rabbit.json5:/rabbit.json5 \
    rabbitmq:3.6 \
    /containerpilot -config /rabbit.json5
2017-07-17T14:04:20.555594719Z loaded config: ...
2017-07-17T14:04:20.556503725Z control: initialized router for control server
2017-07-17T14:04:20.556849563Z event: {Startup global}
2017-07-17T14:04:20.557997452Z rabbitmq.Run start
2017-07-17T14:04:20.579872946Z control: serving at /var/run/containerpilot.socket
2017-07-17T14:04:21.542418124Z
2017-07-17T14:04:21.542448612Z               RabbitMQ 3.6.10. Copyright (C) 2007-2017 Pivotal Software, Inc.
...
(runs and then blocks, all as expected)
```

Then if we check the process tree in the container, we see night of the living dead:

```
docker exec -it rabbit ps afx
  PID TTY      STAT   TIME COMMAND
  269 pts/1    Rs+    0:00 ps afx
    1 pts/0    Ssl+   0:00 /containerpilot -config /rabbit.json5
   13 pts/0    S      0:00 /bin/sh /usr/lib/rabbitmq/bin/rabbitmq-server
  113 pts/0    Sl     0:02  \_ /usr/lib/erlang/erts-8.2.1/bin/beam.smp -W w -A 6
  211 ?        Ss     0:00      \_ erl_child_setup 1048576
  224 ?        Ss     0:00          \_ inet_gethost 4
  225 ?        S      0:00              \_ inet_gethost 4
   89 ?        Zs     0:00 [epmd] <defunct>
   90 ?        S      0:00 /usr/lib/erlang/erts-8.2.1/bin/epmd -daemon
  103 ?        Zs     0:00 [erl_child_setup] <defunct>
  110 ?        Z      0:00 [inet_gethost] <defunct>
  112 ?        Z      0:00 [inet_gethost] <defunct>
  130 ?        Zs     0:00 [erl_child_setup] <defunct>
  137 ?        Z      0:00 [inet_gethost] <defunct>
  143 ?        Zs     0:00 [epmd] <defunct>
  144 ?        Z      0:00 [epmd] <defunct>
  218 ?        Z      0:00 [inet_gethost] <defunct>

**Comment by tgross** [comment]
Ok, I've finally got a reproduction using the following setup.

ContainerPilot configuration:
```json5
{
  consul: "consul:8500",
  jobs: [
    {
      name: "slow-zombies",
      exec: "/slow-zombie.sh"
    }
  ]
}
```

Test target:
```sh
#!/bin/sh

/slow-child.sh &
tail -F # need to make sure job is long-lived
```

And the `slow-child.sh` script:

```
#!/bin/sh

sleep 1 &
sleep 1 &
```

Which results in the following process tree:

```
STAT PPID  PID   COMMAND
S        0     1 /bin/containerpilot -config /etc/containerpilot.json5
S        1    11 {slow-zombie.sh} /bin/sh /slow-zombie.sh
S       11    13 tail -F
Z        1    14 [sleep]
Z        1    15 [sleep]
R        0    19 ps -o stat,ppid,pid,args
```

So the problem is that when the child process is still running, the grandchild get reparented but not reaped. Which was the original hypothesis, but I needed to make sure we could test for it otherwise we'd be at risk of having regressions later.

**Comment by cantoine** [comment]
Awesome, I'm glad the simplified example helped. If there is anything I can do to help or test the fix please let me know.

Thanks!
Chris

**Comment by tgross** [comment]
I've updated the integration test in the PR as follows to make sure we're covering both parts of the problem:
- we need to make sure that reparented processes are being reaped
- we need to make sure that checks aren't being failed with `no child process` errors (which is what we were trying to solve in #222 (with tweaks in #334 and #410).

The heart of the problem is that if we don't reap via the child's process group, then any "reap all of PID1's children" reaper will reap our health checks before we get a chance to get their exit status (technically it races our call to `wait` but we always lose). This results in an error being returned by `wait` and the health check failing when it shouldn't be. This error also masks any _real_ error being returned by the health check, so ignoring it results in a health check passing when it shouldn't be. But if we _do_ reap via the child's process group, then anything that's been reparented isn't getting reaped which is what we're seeing in this ticket.

**Comment by tgross** [comment]
I spent a couple hours this afternoon digging into how other supervisors handle this problem and the answer is mostly "hackishly". Upstart's `expect fork` is particularly illustrative, as it requires the user to give upstart extra configuration values about how many forks to hunt down, etc. So long as ContainerPilot is PID1 and it needs the `WaitStatus` we're going to run into this problem.

My proposed fix is a little radical but I've tested out [a toy solution](https://gist.github.com/tgross/3209021a4c7c69edb8d007167561c401) and it appears to work -- if ContainerPilot is PID1, then before we start any other threads we fork ContainerPilot itself. Then the child reaper runs in PID1 and all the jobs run in the child/worker ContainerPilot. This way when one of our child/worker's children exits (like a health check), then ContainerPilot will get the exit status before it gets reparented to PID1. Without that, then the child processes are already children of PID1 and that's why they're getting reaped in a racy way that causes the "wait no child process" problem.

**Comment by tgross** [comment]
Turns out this solution is somewhat complicated by having our signal handlers. But I think I can make it work.

**Comment by tgross** [comment]
https://github.com/joyent/containerpilot/pull/440 implements the design described in https://github.com/joyent/containerpilot/issues/439#issuecomment-315838435

**Comment by cantoine** [comment]
Tim,

Looks like you got the issue all worked out and the fix is merged, thanks for all of that. Do you know when the next release will be?

**Comment by tgross** [comment]
Sometime this morning.

**Comment by cantoine** [comment]
Awesome, thanks for all your help and the quick turnaround!

**Comment by tgross** [comment]
Released as https://github.com/joyent/containerpilot/releases/tag/3.3.0
