### ISSUE TITLE
set up Travis to deploy master preview releases

### ISSUE THREAD

**Issue by tgross** [joyent/containerpilot#441]
Our releases are versioned according to a loose semver scheme, which means that a human being has to decide what to tag and version the release. However, our master branch contains shipping-quality code at all times. The comment [here](https://github.com/joyent/containerpilot/issues/439#issuecomment-316380593) made me realize that it might be helpful to have a "preview" release for the master branch.

It looks like it's possible to [encrypt a GitHub OAuth token](https://docs.travis-ci.com/user/deployment/releases/#Authenticating-with-an-OAuth-token) for TravisCI to use to deploy a release. But:

> Please note that deploying GitHub Releases works only for tags, not for branches.

Suggests that we can't really do this for the master branch, but there's an `on` conditional field that looks to be able to filter this. I think this might be worth looking into.

**Comment by cheapRoc** [comment]
The scope of the OAuth key that's encrypted should only be for `public_repo` which is an added bonus (yay open source). Otherwise, I think [this link](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A) shows the `on` condition stuff you're looking at.

**Comment by tgross** [comment]
I poked at this a bit and I figured out the reason why you can't use branches rather than tags for the conditional for the `releases` provider, which is that the GitHub API doesn't work without a tag to associate it with. So we'd need a tag too and that gets us back to human intervention to do the tag. So no joy here I think.
