### ISSUE TITLE
Escaping Templating in configuration json

### ISSUE THREAD

**Issue by Smithx10** [joyent/containerpilot#442]
How can I escape templating so I can pass `{{ GetInterfaceIP "eth0" }}` into the consul command?

```    
  "command": ["/usr/local/bin/consul", "agent",
                  "-data-dir=/var/lib/consul",
                  "-config-dir=/etc/consul",
                  "-bind={{ GetInterfaceIP "eth0" }}'",
                  "-rejoin",
                  "-retry-join", "{{ .CONSUL }}",
                  "-retry-max", "10",
                  "-retry-interval", "10s"],
```

Error message:
ESC[36mprometheus_1  |ESC[0m 2017/07/19 22:53:56 Could not apply template to config: template: :19: function "

**Comment by tgross** [comment]
You can escape it by making it a string literal in the golang template. So for example, suppose our configuration file `local.json5` is like the following:

```json5
{
  consul: "{{`{{ mytemplate value }}`}}"
}
```

It'll render like so:

```
containerpilot -config local.json -template
{
  consul: "{{ mytemplate value }}"
}
```

**Comment by Smithx10** [comment]
Thanks Tim,  Totally worked.  I wound up with the following:

      "exec": ["/usr/local/bin/consul", "agent",
                  "-data-dir=/data",
                  "-config-dir=/config",
                  "-bind={{`{{ GetInterfaceIP \"eth0\" }}`}}",
                  "-log-level=err",
                  "-rejoin",
                  "-retry-join", "{{ .CONSUL | default "consul" }}",
                  "-retry-max", "10",
                  "-retry-interval", "10s"],

**Comment by tgross** [comment]
Awesome, good to hear.
