### ISSUE TITLE
Order of deregister 

### ISSUE THREAD

**Issue by ahelal** [joyent/containerpilot#455]
Hi,

I am using container pilot 3.3.1, Not sure if this is a misconfiguration on my side or a bug.

Basically during the container shutdown the *consul-agent* is killed before de-registration of service happens. And I get the following error
`deregistering failed: Put http://localhost:8500/v1/agent/service/deregister/signin-service-staging-249b6c8a109c: dial tcp 127.0.0.1:8500: getsockopt: connection refused`

I can do a registration part of the hook or deregister on terminate of consul-agent, But was wondering if this can be handled by container pilot in a graceful way.

My config file
```{
  consul: "localhost:8500",
  logging: {
    level: "INFO",
    format: "default",
    output: "stdout"
  },
  jobs: [
    {
      name: "configEnv",
      exec: "/usr/local/bin/renderConfigEnv.sh",
      restarts: "never",
    },
    {
      name: "signin-service-staging",
      port: 2045,
      exec: "/signin-service_linux-amd64",
      restarts: 10,
      when: {
        source: "configEnv",
        once: "exitSuccess",
      },
      health: {
        exec: "curl -fsSo /dev/null http://127.0.0.1:2045/status",
        interval: 10,
        ttl: 25,
        timeout: 5,
      },
      tags: [ "signin-service" ],
    },
    {
      name: "consul-agent",
      exec: [ "/sbin/resu", "consul:consul", "--", "/usr/local/bin/consul",
                  "agent",
                  "-disable-host-node-id",
                  "-data-dir=/consul/data/",
                  "-rejoin",
                  "-retry-join", "consul",
                  "-retry-max", "10",
                  "-retry-interval", "10s"],
      restarts: "unlimited"
    }
  ]
}```

**Comment by tgross** [comment]
Jobs are all run concurrently and shutdown via an internal broadcast event, so there's no inherent order to the shutdown. You could create a job that runs on `stopping` that might interject the deregistration, but that's probably not the best approach:

Your Consul agent should be configured with [`leave_on_terminate`](https://www.consul.io/docs/agent/options.html#leave_on_terminate) which forces the agent to leave when it exits, and then service instances associated with that agent will be removed. (Also check [`skip_leave_on_interrupt`](https://www.consul.io/docs/agent/options.html#skip_leave_on_interrupt) if you're testing interactively in your terminal.)

**Comment by tgross** [comment]
Also, I'm not sure what `/bin/resu` is but make sure it's not capturing signals, rather than passing them along to Consul. If Consul isn't getting the `SIGTERM` first, then it'll get `SIGKILL`d and never do a graceful exit.

**Comment by tgross** [comment]
I found that `resu` application and I think that might be the problem. My C is, uh, kinda rusty, but it looks like they're just [calling `execvp`](https://github.com/ben--/resu/blob/2da7553fd0133dced61e459f82b69f29e227236a/src/resu.c#L94) after switching users. They probably should be handling signals too.

**Comment by ahelal** [comment]
@tgross Thank you for all the info. I made an initial test, to catch *SIGTERM* using resu and it seems to work, But will dig into this with more details and get back to you.

**Comment by ahelal** [comment]
@tgross SIGTERM is being propagated correctly to process, but I opted to use  
```json5
jobs: [
  {
    name: "consul-agent",
    exec: "consul agent...",
    stopTimeout: "5s"
  },
  {
    name: "leave-consul",
    exec: "consul leave",
    when: {
      source: "consul-agent",
      once: "stopping"
    }
  }
]
```
Thank you for your input 👍
