### ISSUE TITLE
External Commands in templates

### ISSUE THREAD

**Issue by aleerizw** [joyent/containerpilot#457]
Hi,

Thanks for the project. I wanted to extend the go templates a bit but I figured I would get some feedback before actually implementing the feature.

I want to render the templates based on the output of a command, these variables are rendered at run-time so packaging it with the image doesn't make sense. Currently there's no way of retrieving the value from a shell command or an external binary. 

Consul-template supports [plugins](https://github.com/hashicorp/consul-template#plugin) which is similar to the proposed functionality, it would be really helpful for me if we can support this.

**Comment by tgross** [comment]
The way this has typically been done is by having a job render the template and then reloading the configuration. I'd really rather not re-implement the consul-template plugins rather than telling people to use consul-template proper. Can you elaborate on the use case here?

**Comment by aleerizw** [comment]
My use case has some variables which are sensitive and thus cannot be packaged with the container image. We store these in a secret management system (vault or AWS KMS) and they are retrieved by a client application on the container. 
Currently, I can't run an external command inside the templates so instead of something like:
```
"-encrypt={{ shell(aws kms decrypt .CONSUL_SECRET) }}"
```
I have to create a script which generates the config and makes the external calls.

I hope this explains the use case.

**Comment by tgross** [comment]
We really need to avoid that sort of external task (particular one that hits the network) from being run during ContainerPilot startup. It makes for extremely difficult-to-debug situations in the case of non-fatal failures (like a hang). I'm going to recommend that you use the existing mechanisms described in https://github.com/joyent/containerpilot/issues/457#issuecomment-319431750 to do this.

I'm going to close this proposal, but if you have a workable counter-proposal to try and make the ContainerPilot configuration more easily updatable after it's initially loaded I'd definitely be open to further discussion in a new issue.
