### ISSUE TITLE
Documentation about restarts

### ISSUE THREAD

**Issue by jhmartin** [joyent/containerpilot#470]
https://github.com/joyent/containerpilot/blob/master/docs/30-configuration/32-configuration-file.md#schema has examples of:

```json5
   {
      // a service that doesn't have a "when" field starts up on the
      // global "startup" event by default
      name: "consul-agent",
      // note we don't have a port here because we don't intend to
      // advertise one to the service discovery backend
      exec: "consul -agent -join consul",
      restart: "always"
    }
```

However Containerpilot 3.3.3 objects requires `restarts` instead of `restart`, and complains about `always`:

```unable to parse jobs: job[xyz].restarts field 'always' invalid: accepts positive integers, "unlimited", or "never"```

**Comment by tgross** [comment]
Thanks @jhmartin for the docs-bug report. That's certainly something we'll want to fix. I'm wrapping up for the day but will knock that out tomorrow morning, unless you want to make a PR for it.

**Comment by tgross** [comment]
Doc fix merged.
