### ISSUE TITLE
Discovery: Fix discovery/config.go for TLS-enabled Consul

### ISSUE THREAD

**Issue by sarbash** [joyent/containerpilot#482]
### Hello All.

I've made PR to resolve a trouble with registering in TLS-enabled Consul.

[discovery: fix tls config for Consul](https://github.com/joyent/containerpilot/pull/481)

Please, review it.

Thanks.

**Comment by tgross** [comment]
Hi @sarbash! Thanks so much for the PR! Can you provide here a description of what is going wrong just so that when we look back at this we know why this was done?

**Comment by sarbash** [comment]
Hello again.

Well, this is my config:

```json5
{
  consul: {
    address: "{{.CONSUL_HOST | default "localhost"}}:8500",
    scheme: "https",
    tls: {
      cafile: "CertAuth.crt",   // or CONSUL_CACERT
      clientcert: "Consul.crt", // or CONSUL_CLIENT_CERT
      clientkey: "Consul.key",  // or CONSUL_CLIENT_KEY
      verify: true,             // or CONSUL_HTTP_SSL_VERIFY
    }
  },
```

Unrelated parts were skipped.

This is from log:

```
August 17th 2017, 11:34:03.0002017-08-17T08:34:03.173896914Z service registration failed: Put https://***.***.***.**:8500/v1/agent/service/register: x509: certificate signed by unknown authority
```

I've added `capath` vaue.

The result:

```
August 17th 2017, 11:46:51.0002017-08-17T08:46:51.219278009Z read ./: is a directory
August 17th 2017, 11:46:49.0002017-08-17T08:46:49.128256653Z read ./: is a directory
August 17th 2017, 11:46:47.0002017-08-17T08:46:47.893876245Z read ./: is a directory
August 17th 2017, 11:46:47.0002017-08-17T08:46:47.064615011Z read ./: is a directory
August 17th 2017, 11:46:46.0002017-08-17T08:46:46.449188064Z read ./: is a directory
```

Generally speaking, no success in an interaction with Consul.

**Comment by sarbash** [comment]
I'm sorry that I have no tests to this. All I have are debug logs from CP and answers from Consul in log.
But the code is clear and arbitrary assignments are evident and the logs say me the same.

**Comment by tgross** [comment]
This has been merged and is awaiting release (will be done later today).

**Comment by sarbash** [comment]
Thank you a lot!
I'm happy now :)

**Comment by tgross** [comment]
Released in https://github.com/joyent/containerpilot/releases/tag/3.4.0
