### ISSUE TITLE
putEnv with more then one equal sign will cut string

### ISSUE THREAD

**Issue by ahelal** [joyent/containerpilot#494]
Hi,

As usual thank you guys for a great project.
I am facing an issue when trying to use the `putEnv` with a string with multi equal value

here is an example
```bash
container pilot -putenv POSTGRESQL=localhost:5432/test?user=fred&password=secret&ssl=true";
```

The desired behavior would be to assign `localhost:5432/test?user=fred&password=secret&ssl=true"` to `POSTGRESQL`
the it will ony assign `localhost:5432/test?user`

The issue is due to the limit in [indices](https://github.com/joyent/containerpilot/blob/e2fb5ec4a2c0cdbf8e01cf1a85badd97a0800875/core/flags.go#L36)

I can do PR with the following and this should fix the issue.
```
key, val := strings.Join(pair[0:1], ""), strings.Join(pair[1:], "="))
```

Waiting for your feedback.

**Comment by tgross** [comment]
I feel like we _should_ be able to quote those strings but I checked and that doesn't work. Yeah, we'd love a PR for that fix @ahelal
