### ISSUE TITLE
Display the PID of a job's exec process as an additional logger field

### ISSUE THREAD

**Issue by cheapRoc** [joyent/containerpilot#497]
I'm proposing a feature that would add an additional `pid` logger field of a job's exec'd process. It looks something like this...

```
INFO[0005] 'this is test'                                job=echo-test pid=8346
```

The goal is to delineate between various processes on a system under ContainerPilot's supervision. This also helps display changes in process ID's during reloads, etc.

I've already implemented this so this issue is a stub until I can post the diff (it's inline with another feature).

**Comment by tgross** [comment]
I like this idea! 👍

**Comment by ahelal** [comment]
what about the job name ?

**Comment by tgross** [comment]
> what about the job name ?

That's already included. ref [`jobs/config.go#L253`](https://github.com/joyent/containerpilot/blob/c326edae9cf73151e264f590330a6639586a3fb0/jobs/config.go#L253)

**Comment by cheapRoc** [comment]
This is next up on the list now that #512 has been merged. Look for a new PR soon.
