### ISSUE TITLE
[QUESTION] Service/Check syncing across Consul cluster behind loadbalancer

### ISSUE THREAD

**Issue by cmacrae** [joyent/containerpilot#531]
Hey team 👋 

I've built a few comprehensive software stacks on top of ContainerPilot for use in our infrastructure.  
As we're becoming more reliant on these systems, I recently decided to increase our Consul cluster from a single node to 3.  

However, I ran into an issue as soon as I bumped the cluster up to 2 nodes.  
When ContainerPilot services are checking in with their healthchecks, they're doing so by `PUT`'ing to  `/v1/agent/check/pass/`. [According to this issue](https://github.com/hashicorp/consul/issues/3692) that I raised with the Consul guys, reporting this same problem, this path is node specific.  

In my cluster set-up, I simply have a load balancer fronting an AWS auto scaling group.  
So, any interactions with the Consul endpoint will be randomly routed to any healthy node in the ASG. This has now become problematic, because the `/v1/agent` path is node specific. Services are calling in to report they're healthy, but being routed to an agent that doesn't know about the services or checks.  

[See this issue](https://github.com/hashicorp/consul/issues/3692) for a more comprehensive explanation.  

I don't understand how ContainerPilot can work with a Consul cluster if it's using node specific API paths in its operations.  
Could someone please take the time to explain this to me, or perhaps guide me in a better direction for such a set-up? Perhaps I'm approaching this in the wrong way.  

Thanks in advance for any help on this.  
Please do let me know if there's any other information that will help determine what it is I'm trying to achieve.

**Comment by cheapRoc** [comment]
Great to have you as a part of the community! Don't hesitate to reach out.

Are you running a [Consul _client_](https://www.consul.io/docs/agent/basics.html) agent inside of your ContainerPilot containers?

From your description it sounds like you're focused on running Consul servers, which is great, but there was no mention of running Consul agents within your containers. This is the model that we've targeted and found most useful with ContainerPilot. We launch a single `consul` process within the container for ContainerPilot to use and point ContainerPilot's configuration at `localhost:8500`. The Consul agent at `localhost:8500` acts as a client/proxy and forwards to the main Consul server cluster (your ASG) on behalf of ContainerPilot and your container services.

You can also run the Consul agent on a Docker host system outside of a container that each ContainerPilot instance running on that machine can loop back to. That isn't as portable as running the agent inside a container, but it might also limit the connections to your primary Consul cluster.

Take a look at issue #474, there should be more background info here. Also, there are examples throughout our [autopilot pattern library](https://github.com/autopilotpattern/) ([here's one](https://github.com/autopilotpattern/prometheus/blob/master/etc/containerpilot.json#L33)).

Also, not trying to complicate things but you may want to ditch the load balancer and just reuse the ASG for health and restarting Consul instances. The Consul agent is aware of all membership of your Consul server cluster. Use `retry` parameters to reconnect your agent if a Consul cluster member goes down.

**Comment by cmacrae** [comment]
Hey @cheapRoc 👋   

Thanks for getting back to me on this.  

Right! That makes sense. Believe it or not, I'm actually not even using ContainerPilot in a container set-up. I'm actually using it on VM deployments and deploying as a Systemd unit.  
However, your point still stands. Looks like I'll have to do a bit of reshuffling with the deployment framework I've built to also include a Consul client.  

I'll close this off for now, as I now understand the "issue" I was facing.  

Thanks again for your help!
