### ISSUE TITLE
Allow cron job interval

### ISSUE THREAD

**Issue by dfredell** [joyent/containerpilot#558]
I'm migrating a batch job server into Triton. Currently everything is in Docker and are managed/ monitored by containerpilot. I would like to just put the batch job into the containerpilot ecosystem. This way all of our systems are documented (via containerpilot.json5) and running the same way. The containerpilot provides nice metrics to prometheus when a job fails or is successful. 

So I propose adding a `cron` option in jobs-when section of containerpilot.json5. 
```json
{
  "consul": "localhost:8500",
  "jobs": [
    {
      "name": "DailyCalculation",
      "when": {
        "cron": "0 0 0 * * *"
      },
      "timeout": "10m",
      "exec": "/daily-calc.sh"
    }
  ]
}
```
It could take a string in the cron format `s m h d m w` This way a job can run at midnight everyday, instead of every x minutes from the start of containerpilot.

**Comment by dfredell** [comment]
This looks like it might be helpful https://godoc.org/github.com/robfig/cron

**Comment by cheapRoc** [comment]
Hello again @dfredell, I didn't put 2-and-2 together during or before our call yesterday. 😆 

Thank you for sharing your idea. I'd like to think about it a bit. I respect the thought behind needing cron-like behavior inside a container. Re-using ContainerPilot and interval jobs isn't a far stretch.

My immediate reservation is that ContainerPilot was always meant as an extension of Consul. It brings distributed watches/events and processing that Consul provides to legacy applications. The ultimate goal being not to replace custom software (the things you develop to run inside ContainerPilot) but to enhance software that cannot be easily extended (MySQL, Postgres, etc).

Can you expand on the use case a little more? 
- How do you plan to deploy this and/or use the feature across multiple containers? 
- Is this something you only see using once or twice across a cluster or deployed inside many services/containers?

**Comment by dfredell** [comment]
@cheapRoc,
That is fine, the topics were mostly unrelated.

The containerpilot cron would be created with a Dockerfile and have all its batch scripts inside the container. There would only be one instance of this container running. Then via consul/ containerpilot the metrics would make it to Prometheus then Grafana for monitoring/ alerting. True containerpilot might not be the best choice, really I need something like AWS Lambda or Triton equivalent. Today I'm making a Triton Infrastructure Container and setting up the crontab on that. 
The docker would be deployed via docker-compose into Triton.

So far there is only one container/ use case I would need with a batch. If it doesn't fit the containerpilot model that is fine.

**Comment by cheapRoc** [comment]
I think you're on to something with the infrastructure container. While that might be outside the container infrastructure you're using for other things, it provides a well known and stable environment to run cronjobs.

Going to close this for now but may revisit at some future date with more feedback/push from the community.
