### ISSUE TITLE
[Question]How to disable default metrics and only response custom defined metrics?

### ISSUE THREAD

**Issue by biwugang** [joyent/containerpilot#563]
if add telemetry in config file, it looks like that some default metrics will be add.
for example:
containerpilot_control_http_requests
containerpilot_events{code="ExitSuccess",source="check.hello"} 4465
go_gc_duration_seconds{quantile="0"} 1.5454e-05

How to disable default metrics and only response custom defined metrics?

**Comment by cheapRoc** [comment]
There isn't currently a way to disable ContainerPilot's internal counters and guages. The original intention was for consumers to ignore them if they weren't valuable. This tends to be a decision made when setting up Prometheus.

I'm open to suggestions talking through reasons why we might want to disable them. Is there a reason you had in mind?

**Comment by biwugang** [comment]
for example: 
there is a system which contains a gateway(nginx) and two micro-serveris: serviceA and serviceB
both serviceA and serviceB will use containerpilot Telemetry to expose metrics.

we register the gateway as as one prometheus endpoint.
when prometheus send request to gateway, 
gateway will send request to serviceA and serviceB, and combine serviceA and serviceB metrics,
and then response the combined metrics to prometheus.

in this scenario, promethus will popup the error: 
text format parsing error in line 147: second HELP line for metric name "containerpilot_control_http_requests"

**Comment by misterbisson** [comment]
@biwugang I think we should admit we’ve been struggling with the metrics features. They were designed for ContainerPilot 2.0, but in practice we learned that it’s typically far better for users to run a separate Prometheus exporter, and ContainerPilot 3.0 added specific support for running multiple processes in part to support that pattern. 

The Prometheus exporter features of CP were preserved for compatibility, but it’s far more important for us now to present CP’s internal metrics via that interface. 

I’ll admit this isn’t well documented, and in fact, our docs may be misleading about this, but my suggestion is that you run the exporter as a separate process.

**Comment by cheapRoc** [comment]
@biwugang If there is any other feedback let us know, otherwise I'll close your issue.

**Comment by biwugang** [comment]
I have no other feedback.
Thanks for your help
