### ISSUE TITLE
Building inside a docker container

### ISSUE THREAD

**Issue by flavius** [joyent/containerpilot#565]
Hi

I understand that the makefile uses docker to build the binary - which is fine for scenarios where you want to get started quickly.

I have a setup (a hierarchy of docker images) which already allows me to build all the tools I need, while, very importantly: being able to keep the technical requirements/versions/etc aligned, in the grand scheme of things.

The build system of containerpilot steps out of my control by being "too smart", because it relies on docker. As I said, when I build containerpilot, I'm already inside docker, with golang installed in it.

Can you please provide documentation about how to simply build the binary, and to fail if requirements are not met?

If such a feature cannot be documented because it doesn't exist, maybe it's time to implement it in order to drive adoption in bigger setups?

**Comment by cheapRoc** [comment]
The project uses Docker for building official binary releases which are available as direct downloads on GitHub. If you'd like to build ContainerPilot yourself, you can most likely use something along the lines of the local development build process described by running `make help`...

```
Targets in this Makefile build and test ContainerPilot in a build container in
Docker. For testing (only), use the 'local' prefix target to run targets directly
on your workstation (ex. 'make local test'). You will need to have its GOPATH set
and have already run 'make tools'. Set GOOS=linux to build binaries for Docker.
Do not use 'make local' for building binaries for public release!
```

You'll need to run `make tools` and other adjustments (`GOOS=linux`) but this should give you what you want.

**Comment by cheapRoc** [comment]
Let me know if `make local build` worked for you and whether we need to add better documentation around this. I'm interested in hearing your feedback, otherwise I'll close the issue.
